### PR TITLE
removal of all references to Base Specification class

### PR DESCRIPTION
**Pull request by nicholascar**
As per Issue <https://github.com/w3c/dxwg/issues/641>

### CODE REVIEW

**Review by aisaac — CHANGES_REQUESTED** [review]
I disagee with all references to "base specification" being removed. I am in favour of removing all the references to the class, but it seems this PR goes further.
For example, this PR is changing "base specification" to "standard" in the definition "A named set of constraints on one or more identified base specifications or other profiles". I think that occurrence of "base specification" was alright, and there are probably others.

**Comment by nicholascar** [comment]
Can we put this through and then check against the result that we cover what we need to and improve if not? I'm keen to ensure we purge properly as we have a lot of terminology tangles so that's why I removed occurrences of the phrase "base specification" as well as the actual class. Whether we can cover "base specification" use with "standard" is a good thing to test in another review round.

**Comment by aisaac** [comment]
Hi @nicholascar I would rather avoid any change that would amount to proposing an update to the wording of the agreed definition, and 'base specification' is one of these words. 
First, regarding the matter itself I think 'base specification' is a matter of the role played by another specification rather than a strong statement about the type of resource and I think this is appropriate.
Second, on the meta-level, it avoids another round of terminology discussion. If just because if we remove "specification" and keep only "standard", then we will probably have to re-open the discussion on our understanding of "standard". And honestly the experience of the past week on #275 makes me shiver at the idea of opening an another front.

If you are uncomfortable deciding which "base specification" should be kept, then I'm happy to go through the document and make a proposal.

**Comment by nicholascar** [comment]
Sorry, still not comfortable with the partial retention of the phrase "base specification". The phrase in text is inevitably linked in the mind of the reader to the Base Specification class definition. If we remove the class, we would, at the very least, need to re-examine all uses of "base specification" but, my preference, is to just remove the term altogether and then, on a second reading of the spec without both Base Specification and "base specification" determine appropriate wording.

Can we just use "dct:Standard" as a replacement for "base specification" initially, as per the PR and the reevaluate in a second phase? This is, in my opinion, a cleaner progression.

**Comment by aisaac** [comment]
I'm sorry @nicholascar but I'm not buying the first part of this. If we remove the class BaseSpecification, then how can the reader connect any occurrence of the phrase 'base specification' to a class they can't see?

I think replacing by Standard everywhere is going to resume again all the discussions on standards, and we can't afford this. Again I'm happy making a proposal for changed text. I could even try to replace 'base specification' by 'grounding specification', or 'specification that base the profile' whatever keeps 'specification' in (and the fact that this is a specification the profile is a profile of)

**Comment by aisaac** [comment]
@nicholascar 
In fact I'm not so much against your suggestion of 'remove the term altogether and then, on a second reading of the spec without both Base Specification and "base specification" determine appropriate wording'. It's just that I'm really uncomfortable using "standard" as replacement now, because this will open discussions that will just make us forget what we wanted to do first, and thus lose time.

I'm tempted to suggest a horrible trick that probably only editors can decide on :-)
How about replacing all the remaining occurrences of "base specification" by an artificial token like "[base specification/standard]" (with the brackets) or even "BSS"? This would mark the places we need to discuss in a more neutral way.

**Comment by nicholascar** [comment]
@aisaac: Rob & I discussed this following the meeting just gone. We've agreed to reinstate the text "base specification" as you originally asked for so I'll amend this PR with an extra commit just now to do that.

**Comment by nicholascar** [comment]
textual "base specification" re-added, I think Rob's good to go approving this PR which now addresses @aisaac concerns! Thanks all, I concede that this is now better with those words left in.

**Comment by aisaac** [comment]
Great, thanks, @nicholascar !

**Pull request merged**
