### PR TITLE
DCAT - temporal resolution

### PR DESCRIPTION
**Pull request by dr-shorthair**
Add `dcat:temporalResolution` as discussed in #84

### CODE REVIEW

**Comment by agbeltran** [comment]
Pre-view: https://rawgit.com/w3c/dxwg/dcat-issue84-tres-simon/dcat/index.html#Property:dataset_temporalresolution

**Comment by agbeltran** [comment]
I think it would be helpful to expand the description below [the example](https://rawgit.com/w3c/dxwg/dcat-issue84-tres-simon/dcat/index.html#ex-dataset) to explain what we are representing with ```dct:temporal``` and ```dcat:temporalResolution```.

In [the section describing the property](https://rawgit.com/w3c/dxwg/dcat-issue84-tres-simon/dcat/index.html#Property:dataset_temporalresolution), there is a type ```dct:temporalResolution``` instead of ```dcat:temporalResolution```.

**Comment by agbeltran** [comment]
Following the discussion in #84, should we also add a comment referring to DQV for more complex cases?

**Review by davebrowning — APPROVED** [review]

**Comment by davebrowning** [comment]
As per meeting minutes https://www.w3.org/2019/02/27-dxwgdcat-minutes#x12

**Comment by init-dcat-ap-de** [comment]
The definition is 
"Minimum time period resolvable in the dataset."
The usage note is
"If the dataset is a time-series this should correspond to the spacing of items in the series. For other kinds of dataset, this property will usually indicate the smallest time difference between items in the dataset."

So the definition changes according to the use case. How do I describe the frequency of the time-series and the resolution of the dataset?
How do I know whether "temporal resolution" is the frequency of a time-series or the resolution?

**Comment by makxdekkers** [comment]
Good point. The mention of a time-series is a bit iffy, as we have already said we need to treat that issue more fundamentally in future work.
Could we just simplify the usage note to:
"_This property will usually indicate the smallest time difference between items in the dataset_."
I think this simplified statement could also be seen as including 'spacing of items'.

**Pull request merged**
