### PR TITLE
Verify code examples for consistency

### PR DESCRIPTION
**Pull request by dr-shorthair**
I noticed that we had been inconsistent in our use of the prefix specified for DC Terms - the table in Section 3 says ```dct:``` but the DQV example in chapter 8 all used ```dcterms:```. 

I fixed these. But there are likely to be other inconsistencies, so I'll leave this as a draft for now but must be merged before CR.

### CODE REVIEW

**Comment by dr-shorthair** [comment]
Also generated JSON-LD versions of all the examples.

**Comment by riccardoAlbertoni** [comment]
I have checked for further namespace inconsistencies.  I think there are not. I've just added some prefixes that were used and not declared in the namespace section.
Sorry @dr-shorthair if I have worked directly on your branch,  considered the kind of changes made I hope this is not a problem ...

**Comment by dr-shorthair** [comment]
All good @riccardoAlbertoni that's why I kept my name out of the branch :-) this is just editorial

**Comment by dr-shorthair** [comment]
Note that most of the files here are just automatic conversions from TTL to JSON-LD.

**Review by riccardoAlbertoni — APPROVED** [review]

**Review by davebrowning — APPROVED** [review]
Minor conflict (unrelated to these changes) with gh-pages/index addressed, plus a random reversion in the title

**Pull request merged**
