### PR TITLE
small edits

### PR DESCRIPTION
**Pull request by pwin**
- some small edits and typos
- also, aren't URIs in QSA settings URLs?

### CODE REVIEW

**Comment by larsgsvensson** [comment]
@pwin scripsit:
> also, aren't URIs in QSA settings URLs?

Since all URLs are URIs, I don't really see the point of this specificity here. Can you expand a bit on why you think that change is necessary?

And: You obviously need to update your affiliation information for IPR reasons.

**Comment by larsgsvensson** [comment]
(Removed @agbeltran as a reviewer since she's not a document editor, added @rob-metalinkage for the same reason...)

**Comment by pwin** [comment]
@larsgsvensson  querystrings are part of URLs, and URLs are subject to length constraints. Exceeding the maximum URL length results in 414 error. So I think it is important to be specific

**Comment by nicholascar** [comment]
I've merged the conficts (this PR occuring after othe PRs) but this doen't resolve the substantive issue of the use of URI v. URL.

**Comment by larsgsvensson** [comment]
@pwin would it be OK if we merge the minor edits and open another issue for the URI vs URL questions and address that in the 2PWD?

**Comment by pwin** [comment]
@larsgsvensson  - yes, of course.  Will you create the URL/URI issue, or shall I?  Of course, it is predicated on QSA being an ongoing component of the document.

**Comment by larsgsvensson** [comment]
@pwin scripsit:
> Will you create the URL/URI issue, or shall I?

Please do, since I don't quite understand the second part of your reply:
> Of course, it is predicated on QSA being an ongoing component of the document.

**Comment by nicholascar** [comment]
I have merged conflicts and in so doing fixed a wording issue about a response being of the requested profile or a more general resource, not a more narrow one.

**Review by larsgsvensson — APPROVED** [review]

**Review by nicholascar — APPROVED** [review]

**Pull request merged**
