### PR TITLE
Extending DCAT for services

### PR DESCRIPTION
**Pull request by dr-shorthair**
This PR implements the model shown in https://github.com/w3c/dxwg/blob/dcat-service-simon/dcat/UML/DCAT-summary.png as agreed in meeting of DCAT sub-group meeting 2018-05-25
https://www.w3.org/2018/05/24-dxwgdcat-minutes.html#ResolutionSummary 

4 classes are added: 
- `Resource`
- `DataService`
- `DistributionService`
- `DiscoveryService`

6 properties are added: 
- `catalog`
- `service`
- `accessService` (discussion at #124)
- `servesDataset`
- `endpointLocation` (discussion at #237)
- `endpointDescription` (discussion at #237)

This extension to DCAT is intended to satisfy requirement #56 and the matters discussed in #172 #180 #181, as illustrated in #237 

The text labels and definitions might need some tweaking as discussed, and also the global (domain/range) and local (Restriction) constraints. 

The intention of this pull request is to get the backbone into the RDF representation and into the draft recommendation document, so that we can refer to it while discussing other issues, and to allow us to refine other aspects _in context_ in due course.

### CODE REVIEW

**Comment by dr-shorthair** [comment]
@andrea-perego will you be able to review this?

**Comment by pwin** [comment]
Shouldn't endpointLocation be endpointURL as described by @andrea-perego in #237 ?
"location" suggests geospatial

**Review by andrea-perego — COMMENTED** [review]
Together with @pwin , I would also prefer `dcat:endpointURL`, as reminds `dcat:accessURL` and makes it explicit the it should take as object a URI/URL and not a class instance.

I would also support the inclusion of a generic "Service" class (either by re-using `dctype:Service` or by defining a new class `dcat:Service`).

Said that, I'm fine with merging this PR and address these points later - we just need to create the relevant issues.

**Comment by dr-shorthair** [comment]
1. I'm OK calling it `endpointURL` _provided_ that for all the properties `*URL`, they are corrected to owl:DatatypeProperty with range xsd:anyURI

2. Service was renamed DataService following the discussion in the F2F - @kcoyle seemed to feel quite strongly about that, and also with @danbri in the room we wanted to be clear that we were talking about web- and data-oriented services not hairdressers.

**Comment by andrea-perego** [comment]
@dr-shorthair said:

> 1. I'm OK calling it `endpointURL` _provided_ that for all the properties `*URL`, they are corrected to owl:DatatypeProperty with range xsd:anyURI

I have to disagree here. It would break existing implementations, and I don't think we have any use cases supporting this revision. Moreover, having them as object properties would enable cross-linking of related resources (as services and distributions). 

Using "URL" in the property name is consistent with similar DCAT properties (`dcat:accessURL` and `dcat:downloadURL`, which are object properties), and DCAT users will recognise the pattern. So, I don't see the need of requiring a term to be a datatype property just because it includes "URL" in its name.

> 2. Service was renamed DataService following the discussion in the F2F - @kcoyle seemed to feel quite strongly about that, and also with @danbri in the room we wanted to be clear that we were talking about web- and data-oriented services not hairdressers. 

I tend to agree that we should not allow any type of service, but I don't think we have currently a clear idea of what should be in or out. 

An option, already discussed, and recently suggested by @pwin [in his mail](http://lists.w3.org/Archives/Public/public-dxwg-wg/2018Jun/0058.html), is to say that the scope is limited to online (Web?) services. On the other hand, we have the example of the Core Public Service vocabulary, which is used to describe a (not necessarily online) service delivered by a public institution, and such descriptions are meant to be available in catalogues. I cannot find a strong case to say that we cannot use DCAT for describing these catalogues.

**Comment by dr-shorthair** [comment]
1. I opened a separate issue to discuss the type and range of *URL properties #249 - let's have the conversation there. In this PR there are no changes to `downloadURL` or `accessURL`. 

2. `DataService` is probably the most conservative option for naming. Can we accept it for now and consider again later if more general services also need to be included?

Note I also moved all the classes and properties that were already marked 'deprecated' in DCAT-2014 into the RDF document [dcat2014.ttl](https://github.com/w3c/dxwg/blob/dcat-service-simon/dcat/rdf/dcat2014.ttl), where we are gathering all the axioms removed in the DCAT-rev process. That allows the dcat.ttl document to reflect the current state without any noise (most of the deprecated classes were related to services ...). They can be reinstated later if necessary. 

I'm concerned that merging becomes difficult if we have too many branches open. This one covers what is likely to be the main refactor that we will make in this DCAT revision. It introduces the class `dcat:Resource` interpolated above `dcat:Dataset`, and also includes `dcat:DataService` and sub-classes, and a small number of new properties - `dcat:service`, `dcat:catalog`, `dcat:endpointURL`, `dcat:endpointDescription`, `dcat:accessService` and  `dcat:servesDataset`. The overall shape of these has been accepted by the team, with the explicit understanding that we can and should tidy up details later. My view is that we need to move this material into the gh-branch now so that we can get community scrutiny of the editor's draft. Nothing is final until we publish a rec in a year or so, but it would be helpful to expose this material.

**Comment by dr-shorthair** [comment]
Just spent another hour resolving conflicts through the various branches and merges. 
I believe I have addressed all @andrea-perego comments now, and this should be a good basis for moving forward. Can we merge this into the gh-pages i.e. _Editor's Draft_. 
I don't think the risks are great to expose this now - all details are still subject to potential revision, but the general shape reflects the agreement in Genova and the following telecon. 
@davebrowning @pwin @agbeltran ?

**Review by agbeltran — APPROVED** [review]
I have gone through the changes and they seem ok to me and in line with the discussions. I will merge now - as always, the understanding is that more revisions could arise from further discussions.

**Pull request merged**
