### PR TITLE
conneg doc additions

### PR DESCRIPTION
**Pull request by nicholascar**

### CODE REVIEW

**Comment by rob-metalinkage** [comment]
Happy with the scope - would like to see the incomplete placeholder text sections taken out of normal text and placed in an issue though.

**Review by rob-metalinkage — CHANGES_REQUESTED** [review]
Can we make the placeholder text sections into formal issues to add such content.

**Comment by nicholascar** [comment]
I have moved incomplete text to ReSpec Issues in the next commit

**Review by larsgsvensson — COMMENTED** [review]
Seems OK to me.

**Pull request merged**
