### PR TITLE
dcat:Dataset type

### PR DESCRIPTION
**Pull request by dr-shorthair**
1. remove subclass axiom dcat:Dataset subclass of dctype:Dataset #98 
2. add recommendation to use dct:type to indicate the type or genre of a data set, with value taken from suitable controlled vocabulary (examples provided) #64

### CODE REVIEW

**Review by agbeltran — CHANGES_REQUESTED** [review]
Given the discussion in #64, the current text on dataset types seems too brief. Shouldn't we add more examples apart from this:

```
<p>
	The type or genre of a dataset may be indicated using the <a href="http://purl.org/dc/terms/type">dct:type</a> property:
</p>

<pre>  :dataset-001 dct:type dctype:Text . </pre>
```

**Comment by agbeltran** [comment]
@dr-shorthair looking at your last comment in #64, it seems you weren't intending to close the issue but this PR is just a first step? However, are you intending to close the issue #98 with this PR? Some clarity on this will be helpful.

**Comment by dr-shorthair** [comment]
Yes - PR is a first step. I've made the necessary change to the RDF, and also to section 6 in the Rec document. 

The discussion and examples in section 5 need more work: in particular how to use classifiers from type vocabularies where the items do not have individual URIs.  I think it is useful to merge this PR, but leave #64 open until the requirement has been fully satisfied with more documentation and examples.

**Review by agbeltran — APPROVED** [review]

**Comment by agbeltran** [comment]
OK, thanks for clarifying. Merging now.

**Pull request merged**
