### PR TITLE
PR to address the Dataset publications [RDSP] requirement

### PR DESCRIPTION
**Pull request by agbeltran**
Initial draft to address https://github.com/w3c/dxwg/issues/63

Pre-view: https://rawgit.com/w3c/dxwg/agb-issue63/dcat/index.html#Property:dataset_isReferencedBy

### CODE REVIEW

**Review by riccardoAlbertoni — CHANGES_REQUESTED** [review]
+1 to explicitly mention this property, but I think we should drop the domain for this property as we are borrowing it for Dublin Core and in the original dc term the domain is not dcat:Dataset.

**Comment by andrea-perego** [comment]
I agree with @riccardoAlbertoni .

+1 from me as well to add this property.

**Comment by makxdekkers** [comment]
+1 from me too

**Comment by agbeltran** [comment]
As discussed today (https://www.w3.org/2019/05/08-dxwgdcat-minutes.html), this PR will be modified to:

- [x] move the property to ```dcat:Resource```
- [x] add note to indicate that this is a special case of what is referred in the ```dcat:qualifiedRelation``` property
- [x] remove domain
- [x] add RDF example

Also:
- [x] add item on Change history section
- [x] propagate property in inherited properties lists

**Comment by agbeltran** [comment]
New preview link: https://rawgit.com/w3c/dxwg/agb-issue63/dcat/index.html#Property:resource_isReferencedBy

**Review by andrea-perego — DISMISSED** [review]
Thanks, @agbeltran . I would suggest 2 changes:

1. Remove the reference to Issue #63 . Maybe a link to Issue #63 can be added to the NOTE saying that this is a new property etc.
2. Add the relevant entry in the changelog

**Comment by dr-shorthair** [comment]
- [x] add dct:isReferencedBy to the dcat.ttl RDF file - with the DCAT usage notes and definitions as annotations

**Comment by agbeltran** [comment]
This PR is ready now - note that the link to the example will only work when merged into the ```gh-pages```branch.

**Review by dr-shorthair — APPROVED** [review]

**Review by riccardoAlbertoni — APPROVED** [review]

**Pull request merged**
