### PR TITLE
Ucr profile requirements updated and PubRules tested

### PR DESCRIPTION
**Pull request by jpullmann**
PubRules, links and syntax validation applied. Only errors related to transitory publication status remained (new versioned URL, status header etc. involving the future publication date )

### CODE REVIEW

**Comment by aisaac** [comment]
Hi @jpullmann it seems that the systems wants to link your github account to your w3c profile, see message above. It's strange that this would occur for you only now. It's not your first PR.

I've noted that you've commented several Europeana links that are dead. I shall fix this of course. But before this, which part should I fix? I see these links appearing in two places in the source (around lines 2050-2080 and around lines 2620-2630).

**Comment by agbeltran** [comment]
This extra check was added fairly recently, and that's why previous PRs wouldn't have had a problem.

**Comment by jpullmann** [comment]
Asking Antoine to repair the Europeana links, will reopen afterwards. Resolved the Github/W3C account issue.

**Comment by aisaac** [comment]
europeana links have been fixed by https://github.com/w3c/dxwg/commit/5c9e27bbb6ead8105a79c1d16d5bc20cc5ff8cdd

**Pull request closed without merging**
