### PR TITLE
Addressing issue #1349

### LINKED ISSUE #1349: Align textual descriptions with the DCAT scope
We have still a number of textual descriptions of classes and properties, as well as in other sections of the specification, still referring to datasets and data services as the only resource types in a catalogue.

### PR DESCRIPTION
**Pull request by andrea-perego**
This PR includes proposed revisions to address https://github.com/w3c/dxwg/issues/1349 , plus editorial fixes.

Preview:

https://raw.githack.com/w3c/dxwg/dcat-issue-1349/dcat/index.html

Diff:

https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fdxwg%2Fdcat%2F&doc2=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fdxwg%2Fdcat-issue-1349%2Fdcat%2Findex.html

Summary of changes to the specification:
- Normative sections:
  - Update [§6.1 RDF representation](https://w3c.github.io/dxwg/dcat/#RDF-representation) to point to the RDF representation of DCAT3 - commit https://github.com/w3c/dxwg/pull/1510/commits/e083c64ba351e8a64ae42bd7c31b25fdedf04d04
- Non-normative sections:
  - Refined definition of `dcat:Catalog` in [§5.1 DCAT scope](https://w3c.github.io/dxwg/dcat/#dcat-scope) to make it explicit that the scope of a catalog is not limited to datasets and data services - commit https://github.com/w3c/dxwg/pull/1510/commits/1f50cb076dd6f53a6b3ec7f742536263067218f3
  - Updated link to DataCite resource types in [§5.5 Classifying dataset types](https://w3c.github.io/dxwg/dcat/#classifying-dataset-types) - commit https://github.com/w3c/dxwg/pull/1510/commits/c5a1eb6a696bd9c51419360d5648c4d6d2e5fcce
  - Fixed [Example 8](https://w3c.github.io/dxwg/dcat/#ex-dataset-multiple-types) to correctly specify the value of `dcterms:source` (object property) - commit https://github.com/w3c/dxwg/pull/1510/commits/ae3056defaa8a979df56a867acc3f5f23b9044d3
  - Updated link to DataCite resource types in [§8.1 Indicating common identifier types](https://w3c.github.io/dxwg/dcat/#identifiers-type) - commit https://github.com/w3c/dxwg/pull/1510/commits/4d6aed78a05d26bd29e2c882f349988c7e92a5d7
  - Update [Example 36](https://w3c.github.io/dxwg/dcat/#ex-versioning-with-dcat-and-owl) to show how to use OWL and DCAT to version DCAT3, instead of DCAT2 - commit https://github.com/w3c/dxwg/pull/1510/commits/3491403200f1008aab5249375d64e5307d0f5392
  - Remove comment incorrectly encoded and no longer necessary in [§14.2.1 Conformance to a standard](https://w3c.github.io/dxwg/dcat/#quality-conformance-statement) - commit https://github.com/w3c/dxwg/pull/1510/commits/7c921788d7f1d6ebafea91d76f51783295b57248
  - Added changelog - commit https://github.com/w3c/dxwg/pull/1510/commits/7b1e60be44fb02cf39b9f98dd850ec93491a79e4

Other changes:
- Updated `config.js` - commit https://github.com/w3c/dxwg/pull/1510/commits/250ae80995219d9c94b49f829d3dc70f151b3a54
- Updated `README.md` - commit https://github.com/w3c/dxwg/pull/1510/commits/4a6ff3725fa60d7b3cd62d9320a43bd0d33e5574

To do:
- URIs from the CSIRO registry, starting with http://registry.it.csiro.au/, seem to be broken /cc @dr-shorthair

### CODE REVIEW

**Comment by andrea-perego** [comment]
@dr-shorthair , the URIs from the CSIRO registry, starting with http://registry.it.csiro.au/, seem to be broken.

Should we replace them with other ones?

**Comment by dr-shorthair** [comment]
Indeed. registry.it.csiro.au was decommissioned about 6 months ago. 
Some of the content has been rehoused in https://vocabs.ardc.edu.au/ 
We could add more there if it would be useful for DCAT. 

However, for DataCite and Re3Data it would be best to source them direct, of possible.

**Comment by andrea-perego** [comment]
> Indeed. registry.it.csiro.au was decommissioned about 6 months ago. Some of the content has been rehoused in https://vocabs.ardc.edu.au/ We could add more there if it would be useful for DCAT.
> 
> However, for DataCite and Re3Data it would be best to source them direct, of possible.

Thanks, @dr-shorthair . About DataCite and Re3data, as far as I know they have no HTML and/or RDF representation but only an XML schema + PDF. So, we don't have URIs to be used.

I checked the occurrences of URIs starting with http://registry.it.csiro.au/ , and I tried to find the corresponding ones from https://vocabs.ardc.edu.au/ . The result is the following:


Current URI | Possible replacement
-- | --
http://registry.it.csiro.au/def/datacite/resourceType/Dataset | https://linked.data.gov.au/def/resource-types/Dataset
http://registry.it.csiro.au/def/re3data/contentType/database | Not found
http://registry.it.csiro.au/def/isotc211/CI_RoleCode/distributor | http://linked.data.gov.au/def/iso19115-1/RoleCode/distributor
http://registry.it.csiro.au/def/isotc211/CI_RoleCode/funder | http://linked.data.gov.au/def/iso19115-1/RoleCode/funder
http://registry.it.csiro.au/def/isotc211/DS_AssociationTypeCode/stereoMate | Not found

Could you please indicate which URIs should be used for the missing ones? Also, it seems that some of the URIs use `http://` (ISO 19115-1) and other ones `https://` (DataCite). Which ones should be used?

BTW, strange that the URI of the DataCite resource type code list is 

https://linked.data.gov.au/def/resource-types

Looking at those used for ISO 19115-1, I would have expected something like

https://linked.data.gov.au/def/datacite/resource-type

**Comment by andrea-perego** [comment]
@agbeltran , @davebrowning , @dr-shorthair , @pwin , @riccardoAlbertoni ,

I suggest we review and merge this PR. I'll create a separate issue for the URIs from http://registry.it.csiro.au/

**Review by riccardoAlbertoni — APPROVED** [review]
Thanks, @andrea-perego  for taking care of these tweaks.

**Review by dr-shorthair — APPROVED** [review]

**Comment by rob-metalinkage** [comment]
Lack of stable normative ISO concepts with canonical URI dereferencing behaviours is a major barrier when they form an important part of the legal and/or organisational interoperability layer(s).

Is an antipattern to cite these sort of workarounds unfortunately.  Whilst I have been exploring some concepts around proxy patterns not in a situation where it could help here, its more of a local implementation choice supported by the PROF vocab,

**Pull request merged**
