### PR TITLE
Pull addressing issue #987 

### PR DESCRIPTION
**Pull request by riccardoAlbertoni**
Pull addressing issue #987

### CODE REVIEW

**Review by davebrowning — APPROVED** [review]

**Comment by riccardoAlbertoni** [comment]
@agbeltran: Could you please update the Spanish translations for odrl:hasPolicy?

**Comment by agbeltran** [comment]
@riccardoAlbertoni I've updated the Spanish translations and removed the editorial note, as it is now not relevant anymore

**Review by dr-shorthair — APPROVED** [review]
Are the values of skos:definition the same as the ODRL originals?

**Comment by davebrowning** [comment]
> Are the values of skos:definition the same as the ODRL originals?

Well, not the same words:

ODRL: "Identifies an ODRL Policy for which the identified Asset is the target Asset to all the Rules."

DCAT: "A policy expressing the rights associated with the resource if using the ODRL vocabulary"

but the same meaning in context in my reading....?

**Comment by riccardoAlbertoni** [comment]
> > Are the values of skos:definition the same as the ODRL originals?
> 
> Well, not the same words:
> 
> ODRL: "Identifies an ODRL Policy for which the identified Asset is the target Asset to all the Rules."
> 
> DCAT: "A policy expressing the rights associated with the resource if using the ODRL vocabulary"
> 
> but the same meaning in context in my reading....?

This PR uniforms the skos:definition in ttl to the definition we have in the draft WD,
` skos:definition "An ODRL conformant policy expressing the rights associated with the distribution."@en ;`
 Such a change in the definition was  suggested by the the W3C ODRL Community Group in the feedback  (see https://github.com/w3c/dxwg/issues/949#issue-453002150)

**Comment by riccardoAlbertoni** [comment]
@dr-shorthair: Is still ok if we merge this PR or your question was expressing an objection?

> > > Are the values of skos:definition the same as the ODRL originals?
> > 
> > 
> > Well, not the same words:
> > ODRL: "Identifies an ODRL Policy for which the identified Asset is the target Asset to all the Rules."
> > DCAT: "A policy expressing the rights associated with the resource if using the ODRL vocabulary"
> > but the same meaning in context in my reading....?
> 
> This PR uniforms the skos:definition in ttl to the definition we have in the draft WD,
> ` skos:definition "An ODRL conformant policy expressing the rights associated with the distribution."@en ;`
> Such a change in the definition was suggested by the the W3C ODRL Community Group in the feedback (see [#949 (comment)](https://github.com/w3c/dxwg/issues/949#issue-453002150))

**Comment by riccardoAlbertoni** [comment]
I am merging this as @dr-shorthair's question is superseded by  the discussion in #725, where skos:definition are going to become skos:scopeNote.

**Pull request merged**
