### PR TITLE
Annette dataservices

### PR DESCRIPTION
**Pull request by agreiner**
Reworking data services to offer two child classes, data API and data application.

### CODE REVIEW

**Comment by dr-shorthair** [comment]
@agreiner if you pushed this branch into the the w3c github, we could review it using rawgit.

**Comment by agreiner** [comment]
I don't see a way to do that from a fork. Maybe if you make a branch with that name in the w3c repo, I can switch my PR to aim at that?

**Comment by dr-shorthair** [comment]
Suggest you create the branch and sync the content from your fork there.

**Comment by agreiner** [comment]
I created a new pull request for shipping this to the annette-dataservices branch.

**Comment by davebrowning** [comment]
@agreiner - just to check - you want this merge to go ahead?  [You don't need to wait for an editor - its your working branch so you should just be able to merge your changes in.  Its only merges into gh-pages that have to go through an editor]

**Comment by agbeltran** [comment]
@davebrowning if this is merged into the gh-pages branch, it goes straight into the Editors Draft; we had agreed that PRs are merged by editors, and usually with previous discussion if there is a significant change, as in this PR that we should discuss in today's call (before merging) - thanks

**Comment by agbeltran** [comment]
Actually, this PR could probably be closed as it is replaced by #805 - right @agreiner ?

**Comment by agreiner** [comment]
Whatever the editors want to do is fine by me. If you want to use the w3c/dxwg/annette-dataservices branch, that is fine.

**Comment by agbeltran** [comment]
as the content is the same, we certainly don't need both PRs, so I will close this one...

**Comment by davebrowning** [comment]
Ah, yes, I put my comment on the wrong PR - I meant #805

**Comment by davebrowning** [comment]
#805 is now merged so annette-dataservices branch has the updates captured.

**Pull request closed without merging**
