### PR TITLE
Reviewed and re-structured profile requirements

### PR DESCRIPTION
**Pull request by aisaac**
Trying to adopt the structure proposed at F2F4 and fix some misalignment with the working document at https://docs.google.com/document/d/13hV2tJ6Kg2Hfe7e1BowY5QfCIweH9GxSCFQV1aWtOPg.
Also changing titles and abbreviation to better reflect the intention behind several requirements.
Changed are flagged in notes.

### CODE REVIEW

**Review by kcoyle — CHANGES_REQUESTED** [review]
OK to go, with minor wording changes as sent in email.

**Comment by aisaac** [comment]
As per email sent, I believe that changes in wording (of the requirements themselves) should first be suggested on github or the google doc before being approved here.

**Comment by aisaac** [comment]
I'm adding @larsgsvensson to reviewers for him to check the changes for profile negotiation requirements. I'm not sure how much the latest conneg draft uses the UCR as reference, but I feel I should flag it nonetheless!

**Review by jpullmann — APPROVED** [review]
thanks!

**Pull request merged**
