### PR TITLE
Delete the cardinality as indicated in last meeting resolution

### PR DESCRIPTION
**Pull request by riccardoAlbertoni**
Should we say something about default cardinalities in the note or we better avoid any indication?

### CODE REVIEW

**Comment by agbeltran** [comment]
@riccardoAlbertoni my view is that we need to add a clarification in the figure caption, so that it is immediately clear what the diagram aims to do

**Comment by agbeltran** [comment]
I'm assuming this replaces the diagram in https://github.com/w3c/dxwg/pull/1470, do we still need that other PR?

**Comment by riccardoAlbertoni** [comment]
> @riccardoAlbertoni my view is that we need to add a clarification in the figure caption, so that it is immediately clear what the diagram aims to do

@agbeltran I have added to the caption " Except where specifically indicated,  DCAT does not provide cardinality constraints." Is this what you meant? 

>I'm assuming this replaces the diagram in https://github.com/w3c/dxwg/pull/1470, do we still need that other PR?

This PR will merge into #1470.

**Review by agbeltran — APPROVED** [review]

**Comment by agbeltran** [comment]
thanks, @riccardoAlbertoni - that sounds great

**Comment by riccardoAlbertoni** [comment]
Probably trying to separate things and keep the merging of changes in two steps where first we merge into #1470 and then into gh-pages is too complex. So let's merge this PR  and continue the discussion on #1470.

**Pull request merged**
