### PR TITLE
Adding text from DCAT 1.0

### PR DESCRIPTION
**Pull request by agbeltran**
As requested by @kcoyle, added some of the sections from DCAT 1.0 to have as part of our working document.

### CODE REVIEW

**Comment by dr-shorthair** [comment]
Oh - looks like we both did the same thing - I was given the action in this morning's meeting and did it straight away. I just dropped in the complete text from v1.0, and also went through a cleaned up the sections/headings. I already committed/merged - I skipped the review step as it was a purely mechanical task with zero editorial judgement involved. 
Can you look at https://w3c.github.io/dxwg/dcat/ and check it looks OK as the baseline?

**Comment by agbeltran** [comment]
Thanks @dr-shorthair . Yes, I noticed after I added you as a reviewer. 
I should have committed directly to the repo, but I thought it is always good to follow the review procedure (and had added @kcoyle for that). I also had sent an email to the list about this, but it seems it got missed and I could not join the latest call. I will review your addition.

**Comment by dr-shorthair** [comment]
Thanks @agbeltran - I did a little more tidying (author order now alphabetical; internal citations now follow respec/specref) but will follow the review/pull conventions in future. 

In discussion in the meeting today, it seemed that few people know respec, so I wanted to get that done right asap to set a technology example. Meanwhile, I violated the governance process ...

**Comment by agbeltran** [comment]
Thanks @dr-shorthair - I worked with respec in the past, so happy to make changes in the future.

**Comment by dr-shorthair** [comment]
AFAICT the only significant difference between what you did and what I already pushed is a note

	<p><em>From DCAT 1.0</em></p>

at the top of each section. It would probably be easiest to add these in separately, rather than attempting a merge at this stage? I'd also suggest highlighting them as class="note" rather than using em.  
i.e. 

	<p class="note">From DCAT 1.0</p>

**Comment by dr-shorthair** [comment]
Superseded by #40

**Pull request closed without merging**
