### PR TITLE
DCAT: Editorial fixes

### PR DESCRIPTION
**Pull request by andrea-perego**
Preview: 

https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html

HTML diff:

https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fdxwg%2Fdcat%2Findex.html&doc2=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fdxwg%2Fandrea-perego-dcat-ed-rev%2Fdcat%2Findex.html

Summary of changes:

- Harmonised spelling of "super-class", "sub-class", "sub-property"
- Removed empty `title` attributes
- Removed link text for anchors pointing to sections in the "See also:" rows of the tables with class/property definitions
- Harmonised fragment IDs for the Examples sections
- Added pointers to the relevant example sections in the data service, compression and packaging format sections
- Replaced `^^xsd:string` with `@en` in `rdfs:label`'s examples
- Added new version of geometry and point image examples. They are now larger, and have the same size.
- Moved change note of class dataset just after the section title
- Other minor editorial fixes
- Added change notes to the relevant properties of `dcat:Resource`
- Added datatype to value of `time:numericPosition` in examples
- Added "Revised edition" to field `subtitle` in `config.js`, and removed from title.
- Removed EDITOR'S NOTE from the "RDF representation" section
- Fixed markup for external section references

### CODE REVIEW

**Comment by andrea-perego** [comment]
There's an EDITOR'S NOTE just after the title of section 6 ([RDF representation](https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html#RDF-representation)):

> EDITOR'S NOTE
> The DCAT RDF representation is modularized into several files or graphs to help users access a version of DCAT with only the alignments that they need. This mechanism can also be used to capture different levels of axiomatization, though the status of such proposals has not been finalized. See Issue #134 and the issues enumerated below.

Should this be dropped?

**Comment by dr-shorthair** [comment]
Yes. But the different files should be mentioned in the 'namespace document'.

**Review by dr-shorthair — APPROVED** [review]
You are clearly an editor ...

**Comment by andrea-perego** [comment]
@dr-shorthair said:

> Yes. But the different files should be mentioned in the 'namespace document'.

I'll take care of incorporating the relevant text.

**Comment by andrea-perego** [comment]
> There's an EDITOR'S NOTE just after the title of section 6 ([RDF representation](https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html#RDF-representation)):
> 
> > EDITOR'S NOTE
> > The DCAT RDF representation is modularized into several files or graphs to help users access a version of DCAT with only the alignments that they need. This mechanism can also be used to capture different levels of axiomatization, though the status of such proposals has not been finalized. See Issue #134 and the issues enumerated below.
> 
> Should this be dropped?

EDITOR'S NOTE dropped (commented) via https://github.com/w3c/dxwg/pull/931/commits/44c25169a554120ff8281c831ddd768841a70d82

**Comment by andrea-perego** [comment]
If everybody's happy with the changes included in this PR, I think it can be merged.

**Comment by andrea-perego** [comment]
BTW, about the subtitle of the spec: should we replace "Revised edition" with "Version 2"?

Eventually, this is the name we are going to use to advertise this new version of DCAT.

**Review by riccardoAlbertoni — APPROVED** [review]

**Pull request merged**
