### PR TITLE
update issue reference

### PR DESCRIPTION
**Pull request by rob-metalinkage**
now example exists, issue #642 can be closed, and the substantive issue is now #840 and #842 opened up for discussion.

### CODE REVIEW

**Review by nicholascar — APPROVED** [review]
I'm happy with the Issue updates

**Comment by kcoyle** [comment]
"Give the original issue has been addressed with an example" - @rob-metalinkage I believe that there were edits requested to the example, in particular ones requested by @aisaac. It doesn't look like those were done. Were they?

**Comment by rob-metalinkage** [comment]
there is a new issue to consider those edits #840 - they are general stylistic edits around naming that apply to the set of examples - and to consider it properly people will need to see the examples, and the original issue was tangled up with multiple threads and concerns, so all we are doing is updating this so that we can move forwards with single concern issues. Can we please just follow a process rather than try to solve every problem under every issue and review cycle.

**Review by aisaac — APPROVED** [review]
As per my email at https://lists.w3.org/Archives/Public/public-dxwg-wg/2019Mar/0712.html, considering that I was the only one objecting to the merge during our last call (and now, as it appears, for bad reasons), and considering that @kcoyle 's mail (https://lists.w3.org/Archives/Public/public-dxwg-wg/2019Mar/0712.html) leaves the door open to basic merges this week, I am in favour of merging this PR, which is after all only acting the replacement of one rather messy issue with two cleaner ones.
By the way I am going to  try to populate #840 with the relevant stuff from @kcoyle and I in #642

**Pull request merged**
