### PR TITLE
Editorial revision to sec "Quality Information"

### PR DESCRIPTION
**Pull request by andrea-perego**
...following-up from https://github.com/w3c/dxwg/issues/58#issuecomment-453265635

Changes:
- Editorial changes to section "Quality Information" (no changes done in other sections)
- Added entry for the FAIR Principles paper in `config.js`, plus some editorial fixes.

Preview:

https://rawgit.com/w3c/dxwg/andrea-perego-dcat-quality-information-rev/dcat/index.html#quality-information

Diff:

https://services.w3.org/htmldiff?doc1=https%3A%2F%2Frawgit.com%2Fw3c%2Fdxwg%2Fdcat-issue58-ChangingConformanceExamplesToDWBP-riccardo%2Fdcat%2Findex.html&doc2=https%3A%2F%2Frawgit.com%2Fw3c%2Fdxwg%2Fandrea-perego-dcat-quality-information-rev%2Fdcat%2Findex.html#quality-information

### CODE REVIEW

**Comment by aisaac** [comment]
I've had a look (until 8.2.3 Conformance test results) and have made some editorial suggestions in a separate PR (#653 )
And I've got a question to @andrea-perego about one of his changes: in the section "Degree of conformance" is "The following example" really "derived from the Data on the Web Best Practices [[DWBP]])"? It's not in that document specifically.

**Comment by andrea-perego** [comment]
@aisaac wrote:

> And I've got a question to @andrea-perego about one of his changes: in the section "Degree of conformance" is "The following example" really "derived from the Data on the Web Best Practices [[DWBP]])"? It's not in that document specifically.

Yep, you're right. My fault: I wrongly revised the original sentence. Actually, the example is modelled upon how this is done in GeoDCAT-AP, whereas it is the `prov:Plan` in the example that is derived from DWBP. 

I'm now going to fix this via a commit.

**Comment by riccardoAlbertoni** [comment]
@aisaac and @aisaac 
> I've got a question to @andrea-perego about one of his changes: in the section "Degree of conformance" is "The following example" really "derived from the Data on the Web Best Practices [[DWBP]])"? It's not in that document specifically.

I think there is a misunderstanding on that part, it is the PROV-plan a:ConformanceTest  in the example 4 which was derived by  DWBP not the example contatined in the section.

We might move the sentence "(derived from the Data on the Web Best Practices [DWBP])"  , 
 rewriting the sentece " ... to model the testing activity (e,g., a:TestingActivity), a prov:Plan." as 

"... to model the testing activity (e,g., a:TestingActivity), a prov:Plan (a:ConformanceTest) derived from the Data on the Web Best Practices [DWBP]."

**Comment by andrea-perego** [comment]
@riccardoAlbertoni , @aisaac , please check it now if you are happy with it:

https://rawgit.com/w3c/dxwg/andrea-perego-dcat-quality-information-rev/dcat/index.html#quality-conformance-degree

**Comment by riccardoAlbertoni** [comment]
@andrea-perego wrote 
> Actually, the example is modelled upon how this is done in GeoDCAT-AP, whereas is the prov:Plan in the example that is derived from DXWBP. 

Yes, sorry for having deleted that reference it would be good to have it back.

**Comment by andrea-perego** [comment]
@riccardoAlbertoni wrote:

> Yes, sorry for having deleted that reference it would be good to have it back.

I re-added it in the last commit above (https://github.com/w3c/dxwg/pull/652/commits/38c72e1e453d1bece91fd6c02b60223d028ca9e2).

**Review by riccardoAlbertoni — APPROVED** [review]

**Comment by andrea-perego** [comment]
Thanks for approving the proposed revisions, @riccardoAlbertoni .

I made another commit after that, adding just a reference to the SDW-BP for the example taken from there.

**Comment by aisaac** [comment]
@andrea-perego @riccardoAlbertoni I'm afraid I still don't understand how the prov:Plan a:ConformanceTest is derived from DBWP. Is it in a specific section?

Regarding my original comment on the example (which is now I understand taken from GeoDCAT-AP, and the direct link to the SWD section helps!) I just have one editorial question: can we replace 'mutuated' by 'borrowed'? According to https://www.merriam-webster.com/dictionary/mutuated that word is archaic.

**Comment by riccardoAlbertoni** [comment]
@aisaac wrote
>  I'm afraid I still don't understand how the prov:Plan a:ConformanceTest is derived from DBWP. Is it in a specific section?

The DWBP specifies Best Practices and for each BP suggests how to test it, the suggestions might or might not be machine testable and the level of abstraction is rather high. AFAIK BP specifications and Tests are mixed together, no separate section is provided. 

Thus, the derivation in the example links a plan with the DWBP testing in a very shallow way. The ConformanceTest is rather underspecified in the example. It just says that the ConformanceTest is somehow derived from the DWBP recommendation. 

Probably, you were expecting something more. So far, I have resisted to the temptation of specifying the ConformanceTest more, because as far as I know, 
- there is not a DWBP document prescribing the testing procedure more in details.
-  Prov does not say much about how to structure the plans.   In a recent paper,  I and my colleagues have adopted P-PLAN and [Open Provenance Model for Workflows (OPMW)](http://www.opmw.org/documents.html) for detailing workflows and steps of a prov plan. However, this is one of the possibilities extending the prov rec, and I guess others might have different preferences ...

**Comment by andrea-perego** [comment]
@aisaac wrote:

> I just have one editorial question: can we replace 'mutuated' by 'borrowed'? According to https://www.merriam-webster.com/dictionary/mutuated that word is archaic.

+1 from me. Maybe this can be just done via a direct commit to your branch, @riccardoAlbertoni .

**Comment by riccardoAlbertoni** [comment]
@andrea-perego  wrote
> +1 from me. Maybe this can be just done via a direct commit to your branch, @riccardoAlbertoni .

Yes, I have already done it

**Comment by aisaac** [comment]
@riccardoAlbertoni  thanks for the explanation. I'm afraid I'm still lost however. I understand that the BPs in the DWBP document cannot specify a testing plan in detail, and I'm fine with it. But I'm really struggling how the DBWP as a whole can be the source of any conformance test. I would expect that the derivation would be from specific BPs.

Maybe my issue is more visible with example 7 than with example 5. I'm not sure how one could say that a test that in its title is said to be derived from the INSPIRE regulation would have only one `prov:wasDerivedFrom` statement and that this statement would have DWBP as a whole as an object, which DWBP is probably much more general than INSPIRE.

**Comment by riccardoAlbertoni** [comment]
>@riccardoAlbertoni thanks for the explanation. I'm afraid I'm still lost however. I understand that the BPs in the DWBP document cannot specify a testing plan in detail, and I'm fine with it.

OK

> But I'm really struggling how the DBWP as a whole can be the source of any conformance test. I would expect that the derivation would be from specific BPs.

I am not sure that I had your doubt right, probably not. Anyway,  in my view, `a:conformanceTest` is a plan which checks all the BPs, in fact it is composed by  `a:test1, ..., a:testn` see example 7.  Each of the tests will check for a specific BP and will have a proper derivation from a single BP. Are your comments suggesting that we should make this more explicit?  For example, we could state this before example 4 and renaming    the `a:test1 ...` as  `a:testBP1`, `a:testn` as `a:testBPn`.


> Maybe my issue is more visible with example 7 than with example 5. I'm not sure how one could say that a test that in its title is said to be derived from the INSPIRE regulation would have only one prov:wasDerivedFrom statement and that this statement would have DWBP as a whole as an object, which DWBP is probably much more general than INSPIRE.

Well spotted!
The `dct:title` in `a:conformarmanceTest`  currently referring to INSPIRE should indeed refer to DWBP. I am going to fix this.

**Comment by aisaac** [comment]
@riccardoAlbertoni thanks for the explanation. Yes what you suggest would probably solve my issue! I had indeed not understood at all that the conformance plan was meant to address all the BPs.  So the situation is still vague wrt which test can be implemented, but at least the overal picture is clearer to me now, in the sense that I understand better the connection between the plan and the DWBP document as a whole. (i.e the plan is supposed to address all the recommendations of the document)

**Comment by aisaac** [comment]
Thanks for the update, @riccardoAlbertoni !

**Pull request merged**
