### PR TITLE
Revised Section 9 (License and rights statements)

### PR DESCRIPTION
**Pull request by andrea-perego**
> :warning: To be reviewed and revised by the WG before merging.

Tentative revision to Section 9, as per decision taken during the DCAT subgroup meeting of 21 Nov 2018:

https://www.w3.org/2018/11/21-dxwgdcat-minutes#x03

Related actions: [ACTION-85](https://www.w3.org/2017/dxwg/track/actions/85) & [ACTION-86](https://www.w3.org/2017/dxwg/track/actions/86)

The proposed revision includes the following changes:
- Restructured recommendations to include guidance on the use of dct:accessRights for statement concerning only access rights (see #59, #160, #248)
- Incorporated additional text, in the form of notes, covering the following points: compliance with DWBP, examples of code lists used for access rights, reference to ODRS as an example of a vocabulary defining additional rights-related properties (see #224)
- Add concluding paragraph saying that the actual use of these properties is illustrated in the relevant class definitions

This revision can be previewed here:

https://rawgit.com/w3c/dxwg/andrea-perego-dcat-sec-rights-rev/dcat/index.html#license-rights

To see the HTML diff highlighting the changes:

https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fdxwg%2Fdcat%2Findex.html&doc2=https%3A%2F%2Frawgit.com%2Fw3c%2Fdxwg%2Fandrea-perego-dcat-sec-rights-rev%2Fdcat%2Findex.html#license-rights

### CODE REVIEW

**Comment by andrea-perego** [comment]
2nd revision implemented by commit https://github.com/w3c/dxwg/pull/607/commits/735fc7d7e87cc4232df81cac6f733af5804e5e6e, following the proposal in https://lists.w3.org/Archives/Public/public-dxwg-wg/2018Nov/0825.html

**Comment by agbeltran** [comment]
I removed the link to the [wiki](https://github.com/w3c/dxwg/wiki/License-and-rights), as it is listing the issues rather than adding more discussion.

**Comment by agbeltran** [comment]
@andrea-perego the patterns for license and rights statements are presented as three different scenarios (license, access rights, and all other rights) but then there is a fourth case for when the rights are expressed as ODRL policies. Shouldn't these be presented directly as 4 scenarios?

Also, should this section be informative?

**Comment by agbeltran** [comment]
After further discussion with @andrea-perego and given that the ODRL covers all types of rights and can overlap with any of the three defined scenarios, the clarification that is missing is that the recommendation on the use of ODRL is in addition to the use of one of the relevant ```dct``` term.

So, I am modifying the sentence 

"Finally, in the particular case when rights are expressed via ODRL policies, it is recommended to use use the odrl:hasPolicy property as the link from the description of the catalogued resource or distribution to the ODRL policy."

for

"Finally, in the particular case when rights are expressed via ODRL policies, it is recommended to use use the odrl:hasPolicy property as the link from the description of the catalogued resource or distribution to the ODRL policy, in addition to the relevant ```dct``` property."

**Pull request merged**
