### PR TITLE
RDF and JSON versions generated using OWL-API

### LINKED ISSUE #1100: Wierd Protege 5.0 load issue with lastest versions of dcat.rdf and dcat.ttl - opens as inconsistent
As an add on to #944, I opened both the latest version of dcat.ttl and dcat.rdf by URL from within Protege 5.5.0 Build beta-8.  In both cases, the ontologies loaded OK, but contained spurious Error1, Error2, and Error3 (only in the .rdf version) entities (see screen shot below).

Strangely enough, if I download the files from github and then open them in Protege, I get the very same errors!  However, if I remove the spurious subclass statements, save the file, then reopen it, the errors stay gone!  Since there are no obvious Error# axioms in the online files, this seems quite strange!  Not quite sure where the error is coming from.

Screen Shot 2019-09-26 at 3 09 19 PM

### PR DESCRIPTION
**Pull request by dr-shorthair**
Fixes #1100

### CODE REVIEW

**Review by davebrowning — APPROVED** [review]

**Review by riccardoAlbertoni — COMMENTED** [review]
I  have tried to upload these files on Protege 5.5.0, and they do not arise errors.

However, I've noticed that the following warning appears when loading dcat.rdf, dcat.jsonld

> Illegal redeclarations of entities: reuse of entity http://www.w3.org/ns/dcat#theme in punning not allowed [DataProperty: theme, ObjectProperty: theme]

Such a warning is not present when loading dcat.ttl.
Should we get rid of this?

**Comment by riccardoAlbertoni** [comment]
In case we are considering to regenerate the rdf and json serializations to address my previous comment, I would suggest to do it after accepting the PR #1125 and #1127.

**Comment by andrea-perego** [comment]
@riccardoAlbertoni said:

> In case we are considering to regenerate the rdf and json serializations to address my previous comment, I would suggest to do it after accepting the PR #1125 and #1127.

Which is the status of this PR? I see both PRs #1125 and #1127 have been merged. Can be safely merge also this one?

**Comment by riccardoAlbertoni** [comment]
I think we might want to regenerate the JSON and RDF to include the changes made in PR #1125 and #1127. As far as I have understood no all the usual tools to convert are working as expected.  

@dr-shorthair:  It seems that you have figured out the right combination of tools,  would you mind to taking care of this conversion?

**Comment by dr-shorthair** [comment]
OK - done.

**Review by riccardoAlbertoni — APPROVED** [review]

**Pull request merged**
