### PR TITLE
Recharter 2

### PR DESCRIPTION
**Pull request by pwin**
A proposal for the re-charter of DXWG

### CODE REVIEW

**Review by rob-metalinkage — APPROVED** [review]
No objections to these changes

**Review by riccardoAlbertoni — APPROVED** [review]

**Comment by riccardoAlbertoni** [comment]
The document produced by this HTML  can be seen at https://raw.githack.com/w3c/dxwg/e21356361acccddc45472349fd443bbc3954ceb9/charter/index.html

**Comment by aisaac** [comment]
I'm ok with the big lines of this new charter, but before I can really approve it, I miss info about the status of PROF: where is it?
I'm sorry as I've missed the last calls (and will miss the next one) but I've checked in the recent minutes and didn't see it mentioned, either.

**Review by aisaac — COMMENTED** [review]
I'm ok with the big lines of this new charter, but before I can really approve it, I miss info about the status of PROF: where is it?
I'm sorry as I've missed the last calls (and will miss the next one) but I've checked in the recent minutes and didn't see it mentioned, either.

**Comment by kcoyle** [comment]
@aisaac PROF is covered in this charter (as it was in the previous one) in the "other deliverables" section (3.2), most likely coming in under "Subject to its capacity, the working group may choose to develop additional relevant vocabularies in response to community demand." (Note that we were advised that adding Rec Track deliverables to the charter would make re-charter more difficult, but the group is always free to develop new deliverables if it has the need and capacity to do so.)

**Comment by aisaac** [comment]
@kcoyle thanks for the clarification! I had seen this bullet but I thought it was not very explicit about PROF. But looking at the current charter I realize that this is exactly the same situation, and thus I should be happy with it!

**Review by aisaac — APPROVED** [review]

**Comment by makxdekkers** [comment]
OK with me

**Comment by larsgsvensson** [comment]
I think there's a word or two missing in the last half sentence of "Goals". It currently says

> and to develop to a recommendation the work undertaken in the 2017-2019 charter period on content negotiation by profile.

and I think it should read 

> and to develop to a recommendation **from** the work undertaken in the 2017-2019 charter period on content negotiation by profile.

Best,

Lars

**Review by agreiner — APPROVED** [review]
I'm okay with this.

**Pull request merged**
