### PR TITLE
Removing reference to issue 72

### PR DESCRIPTION
**Pull request by agbeltran**
addressing discussion in #72

### CODE REVIEW

**Comment by agbeltran** [comment]
Pre-view: https://rawgit.com/w3c/dxwg/dcat-issue72/dcat/index.html#profiles

**Review by larsgsvensson — APPROVED** [review]
Works for me. In a later iteration we perhaps should add links to the APs we list.

**Comment by agbeltran** [comment]
Yes, I was waiting for confirmation that this is ok before spending the time to add the references for the APs.

**Comment by larsgsvensson** [comment]
> Yes, I was waiting for confirmation that this is ok before spending the time to add the references for the APs.

OK. Then we can also add a reference to https://lankadedata.se/spec/DCAT-AP-SE (the Swedish DCAT-AP).

**Review by dr-shorthair — APPROVED** [review]

**Pull request merged**
