### PR TITLE
Dcat - RDF examples in TTL and JSON-LD

### LINKED ISSUE #971: JSON examples
Looking at https://www.w3.org/TR/vocab-dcat-2/, it would be valuable to have explicit JSON examples for those wishing to represent in same.  Happy to add this if folks agree/find useful.

### PR DESCRIPTION
**Pull request by dr-shorthair**
Fixes #971

Copied all examples from text into RDF files; validated, and exported copies as JSON-LD. 
A few tweaks in the text to fix syntax errors discovered during validation; 

@riccardoAlbertoni I couldn't quite figure out what was going on with this example right at the end of Section 12 - which is not valid Turtle: 
```
# The graph contains the rest of the statements presented in the previous examples.
a:testResult {
  a:Dataset
    dqv:hasQualityMeasurement :measurement_complianceToDWBP;
    dqv:hasQualityAnnotation :errors .
}
```

I took a guess at line 154 in conformance-standards.ttl - can you check please?

### CODE REVIEW

**Comment by riccardoAlbertoni** [comment]
> Fixes #971
> 
> Copied all examples from text into RDF files; validated, and exported copies as JSON-LD.
> A few tweaks in the text to fix syntax errors discovered during validation;
> 
> @riccardoAlbertoni I couldn't quite figure out what was going on with this example right at the end of Section 12 - which is not valid Turtle:
> 
> ```
> # The graph contains the rest of the statements presented in the previous examples.
> a:testResult {
>   a:Dataset
>     dqv:hasQualityMeasurement :measurement_complianceToDWBP;
>     dqv:hasQualityAnnotation :errors .
> }
> ```
> 
> I took a guess at line 154 in conformance-standards.ttl - can you check please?

@dr-shorthair 
It is expressed in TRIG not TTL https://www.w3.org/TR/trig/, so I update the file consequently. 
I have commented rdf:XMLLiteral(s)  which are not normative in RDF but left the messages they surround.

I do not distinguish between dataset-1, dataset-2, dataset-3, and the overall trig is a little redundant but it is as in the DCAT document. Feel free to change it as you like.

**Review by riccardoAlbertoni — APPROVED** [review]

**Comment by dr-shorthair** [comment]
Ahh - TriG - I had missed that. Shoudl there be a comment nearby mentioning that?

**Comment by riccardoAlbertoni** [comment]
In the spirit of minimizing the changes in the examples  and  DCAT document, we can add  a comment  as in the following

> > ```
> > # The graph contains the rest of the statements presented in the previous examples.
>> # The graph is  expressed according to TRIG syntaxt not TTL (see https://www.w3.org/TR/trig/)
> > a:testResult {
> >   a:Dataset
> >     dqv:hasQualityMeasurement :measurement_complianceToDWBP;
> >     dqv:hasQualityAnnotation :errors .
> > }
> > ```

**Comment by davebrowning** [comment]
Would it be possible to add a json-ld version of the dcat.ttl (and perhaps dcat-external.ttl)?  It would also be good to add an RDF/XML version since this was provided for 2014?  [I know these aren't examples....but while we have the tools to hand...:smile:]

If that's a bad idea then we should probably say why.....

(I've made some assumptions in #881 so we need to ensure consistency....)

**Comment by dr-shorthair** [comment]
Done

**Review by davebrowning — APPROVED** [review]

**Comment by riccardoAlbertoni** [comment]
I have just implemented  the following  in the dcat document and the trig example 
> In the spirit of minimizing the changes in the examples and DCAT document, we can add a comment as in the following
> 
> > > ```
> > > # The graph contains the rest of the statements presented in the previous examples.
> > > # The graph is  expressed according to TRIG syntaxt not TTL (see https://www.w3.org/TR/trig/)
> > > a:testResult {
> > >   a:Dataset
> > >     dqv:hasQualityMeasurement :measurement_complianceToDWBP;
> > >     dqv:hasQualityAnnotation :errors .
> > > }
> > > ```

**Pull request merged**
