### PR TITLE
Replacing dct with dcterms in rdf and creating rdf files for DCAT 3

### LINKED ISSUE #1314: Namespace prefix for DC Terms
In our documentation we are using the prefix `dct:` to denote the Dublin Core Terms namespace, and `dcat:` for DCAT. 
I have found that users often conflate these, probably because the prefixes are so similar.  
I suggest using the prefix `dcterms:` instead.

### PR DESCRIPTION
**Pull request by riccardoAlbertoni**
This  PR  creates the rdf files for dcat3 and turns dct curie into dcterms. 

Usually, we keep the RDFs using the same namespaces as in the HTML. 
Besides, similarly to what we already did when moving from dcat2014 to dcat2, I think it is time to create specific rdf files for dcat3.

### CODE REVIEW

**Comment by andrea-perego** [comment]
> This PR creates the rdf files for dcat3 and turns dct curie into dcterms.
> 
> Usually, we keep the RDFs using the same namespaces as in the HTML.
> Besides, similarly to what we already did when moving from dcat2014 to dcat2, I think it is time to create specific rdf files for dcat3.

I agree.

I think we need also to update the files with the examples.

**Comment by agbeltran** [comment]
We should also update the figure - until we resolve other method, is it easy to regenerate the figure with the new prefixes @dr-shorthair ?

**Comment by riccardoAlbertoni** [comment]
> We should also update the figure - until we resolve other method, is it easy to regenerate the figure with the new prefixes @dr-shorthair ?

I suspect we will change figure 1 more than one time in the next month. PRs on versioning and dataset series are likely to change the figure as well. Perhaps we'd better open a new GitHub issue titled "changes to figure 1"  where we pile the changes on to make them on the figure all at once.  What do you think?

**Comment by agbeltran** [comment]
yes, good point @riccardoAlbertoni ! thanks

**Comment by riccardoAlbertoni** [comment]
@andrea-perego and all: Apparently, DCAT 2 REC points to the GitHub examples directly, so if we change dct in there, we will lose the coherence with the  DCAT 2 REC.

I see three options, 1) we wait for changing the examples; 2) we create a brand new copy of the directory 'examples/' named 'exampleDCAT3',  in which dct is replaced by dcterms and we keep the pointed files in 'examples/' coherent with DCAT 2 REC; 3) we change the namespace and lose the coherence of examples with the current REC, as in the end, having dct in the rec and dcterms in the examples is not a big issue.

 Any preferences?

**Comment by andrea-perego** [comment]
Let's wait for the moment. The issue raised by @dr-shorthair is more on the spec side than in the files of the examples and the RDF.

**Comment by andrea-perego** [comment]
As PR https://github.com/w3c/dxwg/pull/1315 is ready to be merged, I'd merge this one into it.

@riccardoAlbertoni , can I proceed, or do you have other revisions to be added?

**Review by andrea-perego — APPROVED** [review]

**Comment by riccardoAlbertoni** [comment]
yes, we can merge this into the other PR, we will deal with the examples later, following proposal 1.

**Pull request merged**
