### PR TITLE
Add issues fort HTTP OPTIONS and alternative QSA forms

### PR DESCRIPTION
**Pull request by rob-metalinkage**
Added issues #510 and #511 to address Rubens concerns at FPWD stage

### CODE REVIEW

**Review by nicholascar — COMMENTED** [review]
Fine by me. I'll re-write the bit about multiple QSA terms being possible though so say something like "do it this way but use any QSA terms you wish"

**Comment by nicholascar** [comment]
See the wording change in the conneg-doc branch I've made to accommodate multiple QSA terminology: https://github.com/w3c/dxwg/tree/conneg-doc. Indicates that the terms _profile & _mediatype may be replaced however the functionality of the abstract methods must not be absent.

**Review by larsgsvensson — APPROVED** [review]

**Comment by larsgsvensson** [comment]
There was a failing check for IPR for @rob-metalinkage, I guess that's due to repository manager work.

**Comment by rob-metalinkage** [comment]
yes - it was weird but I've reattached my github to W3C and we can ignore this.

**Pull request merged**
