### PR TITLE
Editorial fixes

### PR DESCRIPTION
**Pull request by andrea-perego**
Following from https://github.com/w3c/dxwg/issues/683

- Editorial fixes to [UC32](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fdxwg%2Fucr%2Findex.html&doc2=https%3A%2F%2Frawgit.com%2Fw3c%2Fdxwg%2Fandrea-perego-ucr-ed-rev%2Fucr%2Findex.html#ID32) & [UC33](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fdxwg%2Fucr%2Findex.html&doc2=https%3A%2F%2Frawgit.com%2Fw3c%2Fdxwg%2Fandrea-perego-ucr-ed-rev%2Fucr%2Findex.html#ID33) /cc @agbeltran to review
- Added ADMS, DCAT-AP, and GeoDCAT-AP to the existing approaches for [UC43](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fdxwg%2Fucr%2Findex.html&doc2=https%3A%2F%2Frawgit.com%2Fw3c%2Fdxwg%2Fandrea-perego-ucr-ed-rev%2Fucr%2Findex.html#ID43) /cc @agbeltran to review
- Editorial fixes to section about contributors
- Replaced links with bib refs for standards and specs frequently cited and added relevant entries in `config.js`
- Added `ednote` classes to mark parts including inline the name of the contributor
- Replaced class `note` with `ednote` whenever the note looked like comments to be addressed by the WG instead of guidance for the reader
- Harmonised DCTerms prefix throughout the document (replaced `dcterms:` with `dct:`)
- Added `@id` attribute and `example` class to examples (code snippets only)
- Removed unused attributes on HTML anchors, inherited from the wiki markup
- Replaced links in the running text with explicative text
- Added `CODE` HTML tags to qualified names of properties and classes in the running text
- Fixed broken link reported by Bart Hanssens: http://lists.w3.org/Archives/Public/public-dxwg-comments/2019Jan/0005.html (#701)

Preview:

https://rawgit.com/w3c/dxwg/andrea-perego-ucr-ed-rev/ucr/index.html

HTML diff:

https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fdxwg%2Fucr%2Findex.html&doc2=https%3A%2F%2Frawgit.com%2Fw3c%2Fdxwg%2Fandrea-perego-ucr-ed-rev%2Fucr%2Findex.html

### CODE REVIEW

**Comment by aisaac** [comment]
Thanks a lot for all this work, @andrea-perego !
One process point though: I was not aware of @w3c/dxwg-editors but I guess it's not the right group. To start with, @jpullmann is not in there...
I'm going through your changes and will react in another comment.

**Review by aisaac — APPROVED** [review]
I have quickly looked at the diff and the description of updates, and I approve of them!

I am not sure about the change of references to things like "[DWBP], Section 8.6 (Data Versioning)" but it's probably an improvement, and if we need to improve it later we can still do it then :)

Thanks again @andrea-perego  !

**Comment by jpullmann** [comment]
Many thanks for the corrections and updates, Andrea!

**Comment by andrea-perego** [comment]
@aisaac , @jpullmann , thanks!

**Pull request merged**
