### PR TITLE
Temporal & spatial encodings

### PR DESCRIPTION
**Pull request by dr-shorthair**
This PR adds W3C Basic Geo and OWL-Time equivalents to #807 .

### CODE REVIEW

**Comment by dr-shorthair** [comment]
Another possibility would be to make 
`w3cgeo:location rdfs:subPropertyOf dct:spatial` 
which would allow you to put a `w3cgeo:Point` as the direct content of `dct:spatial` ...

**Comment by dr-shorthair** [comment]
... else just say that `w3cgeo:Point` is a sub-class of `dct:Location` - that's probably the simplest option.

**Comment by dr-shorthair** [comment]
Previews at 
https://rawgit.com/w3c/dxwg/dcat-temporal-spatial-simon/dcat/index.html#Class:PeriodOfTime
https://rawgit.com/w3c/dxwg/dcat-temporal-spatial-simon/dcat/index.html#Class:Location

**Comment by andrea-perego** [comment]
Thanks, @dr-shorthair . I'm adding below the pointers to the HTML diff for seeing the actual changes:

- [Class: Period of time](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fdxwg%2Fandrea-perego-dcat-rev-temporal-spatial-coverage%2Fdcat%2Findex.html&doc2=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fdxwg%2Fdcat-temporal-spatial-simon%2Fdcat%2Findex.html#Class:PeriodOfTime)
- [Class: Location](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fdxwg%2Fandrea-perego-dcat-rev-temporal-spatial-coverage%2Fdcat%2Findex.html&doc2=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fdxwg%2Fdcat-temporal-spatial-simon%2Fdcat%2Findex.html#Class:Location)

I'm happy with the revisions - I would like to do some minor editorial changes, but they can wait until your branch is merged into mine. Moreover, I think that, as we are giving alternative ways for specifying spatial and temporal coverage, it would be useful to explain when each option is supposed to be used.

I have only one concern about the following statement 

````turtle
dct:PeriodOfTime owl:equivalentClass time:ProperInterval .
````

as this would formally modify the DCMI definition. 

I wonder whether here we can follow the same approach you used for `geo:lat` / `geo:long` / `geo:alt` - quoting the relevant usage note:

> Use of this property entails that value of the dct:spatial property is a member of the w3cgeo:Point class from [w3c-basic-geo]. This could be taken to imply that w3cgeo:Point is a subclass of dct:Location

So, re-phrasing:

> Use of this property entails that value of the dct:temporal property is a member of the time:ProperInterval class from [OWL-TIME]. This could be taken to imply that time:ProperInterval is equivalent to dct:PeriodOfTime

**Comment by dr-shorthair** [comment]
After discussion in DCAT call, merging these branches so we can polish it in one place.

**Pull request merged**
