### PR TITLE
Fix typo in Example 15

### LINKED ISSUE #1459: Example 15: mistake in the used URIs?
Hi,

In Example 15 in https://w3c.github.io/dxwg/dcat/#dereferenceable-identifiers the example starts with

```
<https://dcat.example.org/id> a dcat:Dataset;
  adms:identifier  <https://example.org/iddoi> ;
  dcterms:publisher <https://example.org/PoelenJorritH> ;
```

but later in the example the URI  of the publisher is 

```
<https://dcat.example.org/PoelenJorritH> a foaf:Person;
  foaf:name "Jorrit H. Poelen" ;
  adms:identifier <https://example.org/PoelenJorritHID> ;
```

This breaks the graph. Namely the upper part is not connected with the bottem part in the RDF graph. It might be intentional, but the description below the example does not highlight this.

### PR DESCRIPTION
**Pull request by andrea-perego**
Addresses https://github.com/w3c/dxwg/issues/1459

### CODE REVIEW

**Review by riccardoAlbertoni — APPROVED** [review]

**Comment by riccardoAlbertoni** [comment]
We might want to propagate the change in the rdf example files available under the directory dcat/examples and in the text explaining  example 15.

Moreover, I have noticed that in the REC we have used three different name spaces for example URIS: https://example.org/,  http://example.org/, and https://dcat.example.org/ 
Perhaps we should consider to use one only. In case, do we want to deal with the example namespace uniformity in a separate issue?

**Review by agbeltran — CHANGES_REQUESTED** [review]
I agree with Riccardo's comments - line 4020 needs the same change: ```<code>https://example.org/PoelenJorritHID</code>``` to ```<code>https://dcat.example.org/PoelenJorritHID</code>```

**Comment by andrea-perego** [comment]
> We might want to propagate the change in the rdf example files available under the directory dcat/examples and in the text explaining example 15.

Could you please take care of it, @riccardoAlbertoni ?

> Moreover, I have noticed that in the REC we have used three different name spaces for example URIS: https://example.org/, http://example.org/, and https://dcat.example.org/ Perhaps we should consider to use one only. In case, do we want to deal with the example namespace uniformity in a separate issue?

Yes, I think we'd better open a new issue on it.

**Comment by andrea-perego** [comment]
> I agree with Riccardo's comments - line 4020 needs the same change: `<code>https://example.org/PoelenJorritHID</code>` to `<code>https://dcat.example.org/PoelenJorritHID</code>`

Thanks, @agbeltran . Just fixed via https://github.com/w3c/dxwg/pull/1463/commits/3b6f1f377ad330b1e52df3584419beb000c221f9

**Review by riccardoAlbertoni — APPROVED** [review]

**Review by davebrowning — APPROVED** [review]

**Comment by andrea-perego** [comment]
> > I agree with Riccardo's comments - line 4020 needs the same change: `<code>https://example.org/PoelenJorritHID</code>` to `<code>https://dcat.example.org/PoelenJorritHID</code>`
> 
> Thanks, @agbeltran . Just fixed via [3b6f1f3](https://github.com/w3c/dxwg/commit/3b6f1f377ad330b1e52df3584419beb000c221f9)

@agbeltran , could you please check if your happy with this revision, and add your review?

**Review by agbeltran — APPROVED** [review]

**Pull request merged**
