### PR TITLE
Add example on how to combine series and versions

### LINKED ISSUE #1409: Using dcat:next and dcat:version in Dataseries
### Revising a dataset in a Dataserie
Status:

Identifier:

Creator: sde

## Tags
dcat Dataserie pav:version

## Problem statement
Should dcat:prev and dcat:next be updated when a dataset in the serie is revised ?

Let’s consider example  38
```

ex:budget a dcat:DatasetSeries ;
  dcterms:title "Budget data"@en ;
  .
  
ex:budget-2018 a dcat:Dataset ;
  dcterms:title "Budget data for year 2018"@en ;
  dcat:inSeries ex:budget ;
  dcterms:issued "2019-01-01"^^xsd:date ;
  dcat:next ex:budget-2019 ;
  .
  
ex:budget-2019 a dcat:Dataset ;
  dcterms:title "Budget data for year 2019"@en ;
  dcat:inSeries ex:budget ;
  dcterms:issued "2020-01-01"^^xsd:date ;
  dcat:prev ex:budget-2018 ;
  dcat:next ex:budget-2020 ;
  .
  
ex:budget-2020 a dcat:Dataset ;
  dcterms:title "Budget data for year 2020"@en ;
  dcat:inSeries ex:budget ;
  dcterms:issued "2021-01-01"^^xsd:date ;
  dcat:prev ex:budget-2019 ;
  .
```

Now let’s consider that budget-2019 is revised with a new dataset budget-2019-rev1

Dataserie can be updated in different ways

* budget-2019-rev1 can replace budget-2019 in the serie 
  * As a consequence budget-2018 and budget-2020 have to be updated for dcat:next / dcat:prev fields
* budget-2019-rev1 can be inserted in the Dataserie in between budget-2019 and budget-2020 
  * As a consequence, budget-2019 and budget-2020 have to be updated for dcat:next / dcat:prev fields
* No update to the dataserie. 
  * When encountering a dataset is a serie, one must check if a new version is available for this dataset. 
* budget-2019 is turned into a Dataserie and holds budget-2019-rev0 and budget-2019-rev1
  * This seems to be over engineering here

What will be the recommendation?

### PR DESCRIPTION
**Pull request by andrea-perego**
Implements resolution in https://www.w3.org/2022/03/08-dxwgdcat-minutes#r02

- Revised guidance section on dataset series to include the use case from https://github.com/w3c/dxwg/issues/1409
- Updated changelog accordingly

Preview: https://raw.githack.com/w3c/dxwg/dcat-issue-1409/dcat/index.html

Diff: https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fdxwg%2Fdcat%2F&doc2=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fdxwg%2Fdcat-issue-1409%2Fdcat%2Findex.html

### CODE REVIEW

**Comment by riccardoAlbertoni** [comment]
I like the changes made with this PR.
@agbeltran and @andrea-perego: Can we mark this as "Ready to review"?

**Comment by andrea-perego** [comment]
> I like the changes made with this PR. @agbeltran and @andrea-perego: Can we mark this as "Ready to review"?

I'd like to have @agbeltran 's feedback before that.

BTW, we need to add a .ttl + .jsonld file to the folder with the examples. @riccardoAlbertoni , could you please take care of that?

**Comment by agbeltran** [comment]
@andrea-perego thanks for including this, the new text with the example looks good to me.
@riccardoAlbertoni @andrea-perego I'm happy to help by including the .ttl + .jsonld files in the examples folder

**Comment by agbeltran** [comment]
@andrea-perego it seems that the other examples in the Dataset series section are not availble as .ttl or .json-ld files either, right? I'm checking the examples folder as well as https://github.com/w3c/dxwg/tree/dcat-issue-1409/dcat/examples/vocab-dcat-3

**Comment by agbeltran** [comment]
@andrea-perego @riccardoAlbertoni I added the example 39 in the two formats

**Comment by andrea-perego** [comment]
> @andrea-perego it seems that the other examples in the Dataset series section are not availble as .ttl or .json-ld files either, right? I'm checking the examples folder as well as https://github.com/w3c/dxwg/tree/dcat-issue-1409/dcat/examples/vocab-dcat-3

I didn't realise that. Probably, we'd better take care of this and the other missing examples in a dedicated PR.

**Comment by andrea-perego** [comment]
> @andrea-perego @riccardoAlbertoni I added the example 39 in the two formats

Thanks, @agbeltran !

**Comment by agbeltran** [comment]
> > @andrea-perego it seems that the other examples in the Dataset series section are not availble as .ttl or .json-ld files either, right? I'm checking the examples folder as well as https://github.com/w3c/dxwg/tree/dcat-issue-1409/dcat/examples/vocab-dcat-3
> 
> I didn't realise that. Probably, we'd better take care of this and the other missing examples in a dedicated PR.

yes, that's what I thought - only added here the one related to the text

**Comment by riccardoAlbertoni** [comment]
I have noticed that the example in RDF/XML was still missing,  so I have added it.

**Review by riccardoAlbertoni — APPROVED** [review]

**Comment by andrea-perego** [comment]
> I have noticed that the example in RDF/XML was still missing, so I have added it.

Thanks, @riccardoAlbertoni .

**Review by riccardoAlbertoni — APPROVED** [review]

**Review by agbeltran — APPROVED** [review]

**Pull request merged**
