### PR TITLE
Changes to scopeNote for dcat:Resource according to issue #980

### PR DESCRIPTION
**Pull request by agbeltran**
Addressing #980

### CODE REVIEW

**Comment by agbeltran** [comment]
It also addresses some syntacting issues that were causing parsing the ttl file to fail.

**Review by dr-shorthair — APPROVED** [review]

**Review by riccardoAlbertoni — CHANGES_REQUESTED** [review]
please wait for the merge - The TTL still has problems according to the RDFCAt provided by JENA. 
I am afraid that removing the multiline literals ( those between """)  when literals are multi lined worsen the syntax issue.  @agbeltran Is it ok for you if I try to fix this up?

**Comment by agbeltran** [comment]
Sure - I can roll back the syntactic changes but those were giving issues with the OWLAPI parser. I guess I would rely on the Jena one more anyway. I'll see if I get some time to set this up as a Continous Integration check for each PR.

**Comment by riccardoAlbertoni** [comment]
> Sure - I can roll back the syntactic changes but those were giving issues with the OWLAPI parser.

That is inspiring, I am going to check in a separate PR if getting rid of the multiline literals is the key to progress on the issues 944. 
I have already rolled back your changes on multiline literal in my PR #1004, there were also other missing semicolons I have fixed. Just merge my PR #1004  to your  PR #1003, and we should be ok for this issue.

**Comment by dr-shorthair** [comment]
This might be the issue - see https://github.com/w3c/dxwg/issues/944#issuecomment-512512439 
I've fixed it in https://github.com/w3c/dxwg/tree/dcat-issue-944

**Comment by agbeltran** [comment]
OK - I've reverted the syntactic fixes as these are now dealt with in #944 - this PR only addresses #980 and can be merged after review

**Review by riccardoAlbertoni — APPROVED** [review]

**Review by davebrowning — APPROVED** [review]

**Pull request merged**
