### PR TITLE
Substituted introduction from github discussion #417

### PR DESCRIPTION
**Pull request by kcoyle**

### CODE REVIEW

**Comment by aisaac** [comment]
Thanks Karen I think it is good. 

I would limit my feedback here to two comments, as I don't want the discussion to happen here and not in #417 :-)

1. replace "Good metadata practice" by "Good data practice", following up on @agreiner's feedback 

2. use the complete definition from wiki (https://www.w3.org/2017/dxwg/wiki/ProfileContext#Draft_common_definition_for_.22profile.22)

> We define a profile generally as named set of constraints on one or more identified base specifications, including the identification of any implementing subclasses of datatypes, semantic interpretations, vocabularies, options and parameters of those base specifications necessary to accomplish a particular function.

I know it's imperfect, but after so much discussion I think it would be a pity not to use it and then be drawn in the same discussions...

Finally I see there's little from @pwin's suggested text (as you've cited at https://github.com/w3c/dxwg/issues/417#issuecomment-427256227). But indeed I find it hard to integrate with your text. Maybe right at the beginning?

**Comment by aisaac** [comment]
Flagging that @agreiner 's comment may bring even more motivation to take onboard more of Peter's text :-)

**Review by rob-metalinkage — CHANGES_REQUESTED** [review]
"outline of the margin of a thing" is bloated and an oxymoron i feel - suggest "outline of a thing"  

As @aisaac points out - we spent ages agreeing a definition of a profile which meets the Use Cases we have - we really dont have an excuse or time to start again, unless we have strong evidence that this is inconsistent with some requirement, and a proposal to update it.  Otherwise it needs to be introduced verbatim early as possible in the document,.

**Review by nicholascar — CHANGES_REQUESTED** [review]
Minor functional edit: [vocab-dcat-2] must be changed to [[vocab-dcat-2]]

Minor grammatical edit: "...as means of accessing data. It is silent on whether a distribution should be in a particular serialization, or set of serializations." --> "...as means of accessing data; it is silent on whether a distribution should be in a particular serialization, or set of serializations.".

Minor functional edit: "...SKOS concept, it does not specify a particular SKOS [skos-reference] concept scheme..." should be "...SKOS [[skos-reference]] concept, it does not specify a particular SKOS  concept scheme..." i.e. moving SKOS ref to first mention and also using double [[, ]] for ReSpec.

Minor grammar: "Other vocabularies such as Dublin Core Terms [DCTERMS] are..." --> "Other 
vocabularies, such as Dublin Core Terms [DCTERMS], are..."

Minor functional edit: [DCTERMS] --> [[DCTERMS]]

Please just take these minor points as OK and I'll include fixes for them in a follow-on PR in the next few hours.

**Comment by nicholascar** [comment]
I've included the text from this PR in another PR with the minor edits I suggested above so please reject this PR and use that one! Currently stages in Branch [profile-guidance-doc](https://github.com/w3c/dxwg/tree/profile-guidance-doc) with commit https://github.com/w3c/dxwg/commit/2f1ce43f43408c17ca3d78bd01851d0ddd9219ff

**Comment by aisaac** [comment]
Hi @nicholascar your new PR seems to be missing my own suggestions above, unless I'm mis-reading the PR over the PR? Anyway we should perhaps wait until the discussion at #417 has stabilized.

**Comment by pwin** [comment]
"it is silent" really means "there is no mention of", surely?

**Comment by nicholascar** [comment]
@aisaac Just give me another hour or so before I put in the PR and I'll include your suggestions. I'm just handing a bit of a "Issue Dedt" of a lot of issues listed but not placed in the doc yet first!

**Comment by aisaac** [comment]
@nicholascar ok now I understand better (also I guess it answers my comment on #428). This said I would still separate your coming PR on issue debt and the one on the intro, as I think the intro still needs some debating in issue #417, while I'd happily approve some of your other 'debt' changes asap!

**Review by aisaac — CHANGES_REQUESTED** [review]
Sorry I had not understood that my previous comment was not a review. So I guess this does it with a link to the comment: https://github.com/w3c/dxwg/pull/446#issuecomment-427430817
But I believe anyway it is perhaps best to wait until more discussion has happened at #417

**Comment by kcoyle** [comment]
Closing because covered in #451

**Pull request closed without merging**
