### PR TITLE
Draft of sentence addressing issues #90 and #93 about versions

### PR DESCRIPTION
**Pull request by riccardoAlbertoni**
Dear Alejandra and Jaro, 
I have drafted a couple of sentences addressing issues #90 and #93 about versioning. 

Since as far as I have understood you are working on the section related to versioning, I wonder if you want to include it in your proposal about versioning.

Thanks a lot, 
Riccardo

### CODE REVIEW

**Comment by dr-shorthair** [comment]
And I added another short paragraph providing a link to qualified-relation as a potential solution pathway.

**Comment by dr-shorthair** [comment]
Marked as non substantive for IPR from ash-nazg.

**Review by dr-shorthair — APPROVED** [review]

**Review by pwin — DISMISSED** [review]
typo in second sentence - "relationshp" but otherwise is fine

**Review by davebrowning — APPROVED** [review]
Typo now addressed - looks good to go

**Pull request merged**
