### PR TITLE
updating affiliation to include previous one

### PR DESCRIPTION
**Pull request by agbeltran**

### CODE REVIEW

**Review by davebrowning — APPROVED** [review]

**Review by riccardoAlbertoni — APPROVED** [review]

**Review by davebrowning — COMMENTED** [review]
Ooops - that's the implementation report config.js, not the REC

**Review by davebrowning — CHANGES_REQUESTED** [review]
We also need to do this to the recommendation.....

**Review by riccardoAlbertoni — APPROVED** [review]

**Comment by davebrowning** [comment]
I think this is okay now (I've had to remove the note but I've hacked it by adding the words to the current affiliation).  It looks okay for the implementation report: http://raw.githack.com/w3c/dxwg/agb-affiliation/dcat-implementation-report/index.html . Waiting for the cache to expire for the dcat document itself.

**Comment by davebrowning** [comment]
Spec looks okay now: http://raw.githack.com/w3c/dxwg/agb-affiliation/dcat/index.html
@agbeltran - does this pass muster for now?

**Review by davebrowning — APPROVED** [review]

**Comment by agbeltran** [comment]
Fine by me - I was following the suggestion [here](https://github.com/w3c/respec/issues/2561) about how to deal with previous affiliations - I'll do the same for the spec

**Comment by agbeltran** [comment]
I see that you did the spec too, thanks @davebrowning !

**Comment by davebrowning** [comment]
> Fine by me - I was following the suggestion [here](https://github.com/w3c/respec/issues/2561) about how to deal with previous affiliations - 

Yeah, I read that but it was scrambling respec - or at least something was....  

[Okay, I was stupid - it wasn't the note, it was a missing comma]

**Pull request merged**
