### PR TITLE
Fixed warning on deprecation of respec-w3c-common

### PR DESCRIPTION
**Pull request by andrea-perego**
As per https://github.com/w3c/respec/issues/2889 and https://github.com/w3c/respec/wiki/respec-w3c-common-migration-guide

Preview here:

https://raw.githack.com/w3c/dxwg/andrea-perego-fix-respec-w3c-common-warning/dcat/index.html

### CODE REVIEW

**Review by agbeltran — APPROVED** [review]

**Comment by agbeltran** [comment]
@andrea-perego comparing this branch (https://raw.githack.com/w3c/dxwg/andrea-perego-fix-respec-w3c-common-warning/dcat/index.html) with master (https://w3c.github.io/dxwg/dcat/) I noticed that the ORCIDs have disappeared for most of us - could this be related with the migration issue?

**Comment by andrea-perego** [comment]
> @andrea-perego comparing this branch (https://raw.githack.com/w3c/dxwg/andrea-perego-fix-respec-w3c-common-warning/dcat/index.html) with master (https://w3c.github.io/dxwg/dcat/) I noticed that the ORCIDs have disappeared for most of us - could this be related with the migration issue?

Thanks for spotting this, @agbeltran . Actually, the ORCID link is there, but the (SVG) icon is not loaded for some reasons.

I'll raise this issue in the ReSpec repo. Until it will be fixed, I would keep on hold this PR.

**Comment by andrea-perego** [comment]
> I'll raise this issue in the ReSpec repo. [...]

Done: https://github.com/w3c/respec/issues/3129

**Comment by andrea-perego** [comment]
Just fixed https://github.com/w3c/respec/issues/3129#issuecomment-697269370 :

https://raw.githack.com/w3c/dxwg/andrea-perego-fix-respec-w3c-common-warning/dcat/index.html

Unless any of finds other issues, I think we can merge this one.

**Review by riccardoAlbertoni — APPROVED** [review]

**Comment by agbeltran** [comment]
all looks good now, thanks @andrea-perego and @riccardoAlbertoni for merging

**Pull request merged**
