### PR TITLE
Clarify UML summary diagram, and figure caption

### PR DESCRIPTION
**Pull request by dr-shorthair**
Responding to #347 
See preview at https://rawgit.com/w3c/dxwg/dcat-issue347-simon/dcat/index.html#vocabulary-overview

### CODE REVIEW

**Review by agbeltran — APPROVED** [review]

**Comment by agbeltran** [comment]
Thanks @dr-shorthair - to me, the clarification about the UML diagram and OWL interpretation is enough and this could be merged. @kcoyle let us know if you have further comments

**Comment by kcoyle** [comment]
Is it useful to add "as indicated with '::'" or is that a notation that everyone will recognize? Also, the text got caught in an "align=center" that you might want to fix before merging. But basically, I approve.

**Comment by agbeltran** [comment]
@dr-shorthair could you please add in the diagram the property 'dct:creator' in 'dcat:Dataset'? (BTW, this would need to be moved to 'dcat:Resource' and I can open an issue about that).

**Comment by dr-shorthair** [comment]
OK - done.

**Pull request merged**
