### PR TITLE
Dcat issue174 ttl riccardo

### PR DESCRIPTION
**Pull request by riccardoAlbertoni**
Please, Alejandra, consider merging this PR in your Branch.

It fixes conflicts with the gh-pages duo to the remotion of DataService subclasses;  adds missing language tags; and removes some illegal carriage return in text; adds Andrea and me as contributors;

### CODE REVIEW

**Comment by davebrowning** [comment]
@riccardoAlbertoni - we've fallen over each other on this one.  I've merged the original into the master

**Comment by riccardoAlbertoni** [comment]
> @riccardoAlbertoni - we've fallen over each other on this one. I've merged the original into the master

Yes I have noticed ;) I was trying to move my suggestions into gh-pages by cherry-picking from my PR, but I can't manage. I think we have two possibilities: 
A) I redo the work on the current gh-pages, or  B) we revert your commit and merge.
 A requires I redo all changes from my PR but  probably it is also more clean, don't you think?

**Comment by davebrowning** [comment]
Yes, I think (A) is more clean.  [All those @en.....]  If that's okay?

**Comment by riccardoAlbertoni** [comment]
Ok for me, I'll work on that ;)

**Comment by riccardoAlbertoni** [comment]
This PR has been superseded by https://github.com/w3c/dxwg/pull/862

**Pull request closed without merging**
