### PR TITLE
Add Czech translation

### PR DESCRIPTION
**Pull request by jakubklimek**
@davebrowning I am not sure whether or not to translate the `dct` imports at the bottom of the document or whether they will be removed later.

### CODE REVIEW

**Comment by dr-shorthair** [comment]
@jakubklimek I wonder if you could resolve conflicts?

**Comment by jakubklimek** [comment]
@dr-shorthair I resolved the conflicts. I suggest this is merged before any other conflicts arise.

**Review by riccardoAlbertoni — APPROVED** [review]

**Review by dr-shorthair — APPROVED** [review]

**Comment by dr-shorthair** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by dr-shorthair** [comment]
Thanks a lot @jakubklimek

**Pull request merged**
