### PR TITLE
Update summary diagram -

### LINKED ISSUE #1365: The prefix of DC terms is dcterms in the text and dct in the class diagram

### PR DESCRIPTION
**Pull request by dr-shorthair**
Fixes #1365 

change dct: to dcterms:
add DCAT3 attributes

### CODE REVIEW

**Comment by agbeltran** [comment]
Preview here to facilitate review: https://raw.githack.com/w3c/dxwg/dcat-issue-1365/dcat/index.html#dcat-scope

**Review by agbeltran — APPROVED** [review]

**Review by andrea-perego — APPROVED** [review]

**Review by riccardoAlbertoni — COMMENTED** [review]
- The diagram includes terms from the qdcat namespace ( e.g. the last terms in the dataset class).  Probably I have missed the discussion on these terms,  but they are not mentioned in the rest of the document, Do they really need to be included in the diagram?
- Terms from DQV have been included in the diagram. That seems to change the rule of thumb we followed in DCAT 2.  In DCAT2 we included only the normative terms in the diagram leaving out terms that haven't the normative status. Similarly,  we did not include DQV terms in the list of properties.  I wonder if, including them in the diagram, we want to change the "rule of thumb" for inclusion?

**Comment by riccardoAlbertoni** [comment]
This also relates to #1320

**Comment by andrea-perego** [comment]
> * The diagram includes terms from the qdcat namespace ( e.g. the last terms in the dataset class).  Probably I have missed the discussion on these terms,  but they are not mentioned in the rest of the document, Do they really need to be included in the diagram?
> * Terms from DQV have been included in the diagram. That seems to change the rule of thumb we followed in DCAT 2.  In DCAT2 we included only the normative terms in the diagram leaving out terms that haven't the normative status. Similarly,  we did not include DQV terms in the list of properties.  I wonder if, including them in the diagram, we want to change the "rule of thumb" for inclusion?

I've actually missed these terms when reviewing the diagram.

I think the diagram should indeed only include the terms described in Section 6. The terms with the qdcat prefix are new also to me.

**Comment by dr-shorthair** [comment]
Apologies - I have removed the stray attributes from the diagram (they were from an application project)

**Review by riccardoAlbertoni — APPROVED** [review]

**Comment by riccardoAlbertoni** [comment]
> Apologies - I have removed the stray attributes from the diagram (they were from an application project)

Thanks for correcting this, Simon. I think we can merge this, independently whether we want or not to have a diagram in an open format, the new diagram you prepared makes the document more consistent with the latest updates.

**Pull request merged**
