### PR TITLE
Add recommendations on the URIs to be used with dcterms:conformsTo

### LINKED ISSUE #1020: Minor editorial comments on DCAT CR candidate
First of all: Kudos to the editors! The CR candidate is a great piece of work.

Minor nits:

1. [4. Conformance](https://w3c.github.io/dxwg/dcat/#conformance): The last bullet point in the list of conformance criteria reads very differently from the other ones.
> A data catalog conforms to DCAT if:
* DCAT-compliant catalogs MAY include additional ...

I propose to take that bullet point out of the list, like
> * All classes and properties defined in DCAT are used in a way consistent with the semantics declared in this specification.
DCAT-compliant catalogs MAY include additional non-DCAT metadata fields and additional RDF data in the catalog's RDF description.

2. [4. Conformance](https://w3c.github.io/dxwg/dcat/#conformance): I think it would be helpful to implementers to explicitly specify which URI to use to indicate that a catalogue conforms do DCAT 2. Would
```
my:catalogue dct:conformsTo <https://www.w3.org/TR/vocab-dcat/>
```
be correct?

3. Figure 1: The relation `dcat:record` from `dcat:Catalog` to `dcat:CatalogRecord` has the cardinality `1..n`. Shouldn't that be `0..n`? (Otherwise it would be mandatory to have at least one catalogue record, while the [usage note for `dcat:CatalogRecord`](https://w3c.github.io/dxwg/dcat/#Class:Catalog_Record) explicitly says: "This class is optional and not all catalogs will use it."

4. In [§6.3.2 Property: themes](https://w3c.github.io/dxwg/dcat/#Property:catalog_themes), the usage notes has a hyphen in "linked-data". This is the only place where this term is hyphenised; all other occurences spell it "linked data".

5. In the definition of [§6.3.6 Property: catalo](https://w3c.github.io/dxwg/dcat/#Property:catalog_catalog), there is no period/full stop at the end of the sentence (the other definitions have one).

6. In the second usage note of [§6.4 Class: Cataloged Resource](https://w3c.github.io/dxwg/dcat/#Class:Resource), there is no period/full stop at the end of the sentence (the other usage notes have one).

7. In [Example 36](https://w3c.github.io/dxwg/dcat/#ex-conformance-degree-percentage), I think that `iso:inherentandSystemDependentDataQuality a dqv:Category ;` should read `iso:inherentAndSystemDependentDataQuality a dqv:Category ;` (inherent __And__ System Dependent ...)

8. In [Example 40](https://w3c.github.io/dxwg/dcat/#ex-conformance-test-error) you use `dc:format "text/xml"`. I don't think we should point people to deprecated media types and propose to use `dc:format "application/xml"` instead.
And I think there is a comma missing in the last sentence of [§12.2.3](https://w3c.github.io/dxwg/dcat/#quality-conformance-test-results): It currently reads "Of course, the above modelling patterns can represent any quality tests not only conformance to standards." I think that should be "Of course, the above modelling patterns can represent any quality tests**,** not only conformance to standards."

9. In the Note at the end of [§13](https://w3c.github.io/dxwg/dcat/#qualified-forms), there either is an "s" too many in "the context resources is a member", should read "the context resource is a member".

10. In the references section you point [DCAT-AP.de] to https://govdata.de/standardisierung. I think the canonical reference to the spec is https://dcat-ap.de/def/.

### LINKED ISSUE #1225: Collate existing practice in use of dct:conformsTo with DCAT
The target for dct:conformsTo is an identifier for a specification. In attempting to implement DCAT (and PROF) establishing canonical URIs for a range of well known specifications is not trivial. 
Can people implementing DCAT please advise how they are doing this now, and if possible publish links to the sets of specifications they have identified. 

this relates to #1146 #1211 #1130 #990

### PR DESCRIPTION
**Pull request by andrea-perego**
The request of providing guidance on the URIs to be used with `dct:conformsTo`, in order to ensure they are harmonised, has been raised in a number of issues: https://github.com/w3c/dxwg/issues/1020 , https://github.com/w3c/dxwg/issues/1130 , https://github.com/w3c/dxwg/issues/1211 , https://github.com/w3c/dxwg/issues/1225

This PR includes some guidelines about the URIs to be used, by adding a few paragraphs at the end of §13.2.1 ("Conformance to a standard"). 

It is just a draft - please review.

Preview: https://raw.githack.com/w3c/dxwg/dcat-issue-1225/dcat/index.html#quality-conformance-statement

Diff: https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fdxwg%2Fdcat%2F&doc2=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fdxwg%2Fdcat-issue-1225%2Fdcat%2Findex.html#quality-conformance-statement

### CODE REVIEW

**Comment by jakubklimek** [comment]
Wouldn't it make sense for SPARQL to indicate https://www.w3.org/TR/sparql11-protocol/ rather than the query spec from the data service point of view?

**Comment by andrea-perego** [comment]
@jakubklimek said:

> Wouldn't it make sense for SPARQL to indicate https://www.w3.org/TR/sparql11-protocol/ rather than the query spec from the data service point of view?

Makes sense to me. This is also what is used in https://github.com/OSGeo/Cat-Interop/blob/master/LinkPropertyLookupTable.csv

@agbeltran , @davebrowning , @dr-shorthair , @riccardoAlbertoni , @pwin , any objections if we update the relevant examples accordingly?

**Comment by andrea-perego** [comment]
About the URI to be used to specify conformance with OWL, at the moment we are using https://www.w3.org/TR/owl2-overview/ in the examples.

Not sure it is the best option. Unfortunately, there's not a TR for the OWL2 ontology, similar to what was available for OWL: https://www.w3.org/TR/owl-semantics/

The closest is probably https://www.w3.org/TR/owl2-syntax/ 

WDYT?

**Comment by jakubklimek** [comment]
I think that at the level of a dataset, https://www.w3.org/TR/owl2-overview/ is probably fine, as it is intended more like a link to a human-readable document rather than something an application would use to automatically determine how to communicate with the endpoint, as it is in the case of data service specification.

**Comment by riccardoAlbertoni** [comment]
> @jakubklimek said:
> 
> > Wouldn't it make sense for SPARQL to indicate https://www.w3.org/TR/sparql11-protocol/ rather than the query spec from the data service point of view?
> 
> Makes sense to me. This is also what is used in https://github.com/OSGeo/Cat-Interop/blob/master/LinkPropertyLookupTable.csv
> 
> @agbeltran , @davebrowning , @dr-shorthair , @riccardoAlbertoni , @pwin , any objections if we update the relevant examples accordingly?

No objections

**Review by riccardoAlbertoni — APPROVED** [review]

**Comment by dr-shorthair** [comment]
I think I was responsible for originally creating that example. I was not confident I had got it right, so am grateful for the comments and guidance here. @jakubklimek looks like you are across this much better than me - thanks. I agree with the change.

**Comment by andrea-perego** [comment]
Thanks, @riccardoAlbertoni & @dr-shorthair . Revision implemented via commit https://github.com/w3c/dxwg/pull/1310/commits/c0accd9ebce5cb0fe21ce434e8213953b52071cf

PR ready for review.

**Review by dr-shorthair — APPROVED** [review]

**Review by riccardoAlbertoni — APPROVED** [review]
I think we can merge it

**Pull request merged**
