### PR TITLE
Updated PROF alignments, as per DXWG wiki

### PR DESCRIPTION
**Pull request by nicholascar**
In time for 2PWD

### CODE REVIEW

**Review by rob-metalinkage — COMMENTED** [review]
can you provide link to the preview please?

**Comment by nicholascar** [comment]
See this preview of the changed document: https://raw.githack.com/w3c/dxwg/prof-alignments/profilesont/index.html#alignments

**Comment by rob-metalinkage** [comment]
I think that the section "PROF is considered a specialisation of the revised version of the Dataset Catalogue Vocabulary [VOCAB-DCAT-2] for the purpose of cataloguing profiles. With this in mind, the main PROF classes - Profile and Resource Descriptor, specialised (are sub classes of) DCAT's Resource and Distributions respectively."   needs to be preceded with a statement that the alignment is not normative, but is provided as a recommended way to consider general metadata needs when describing profiles.

**Comment by andrea-perego** [comment]
Not sure about this statement:

> [...] the fact that both prof:Profile and adms:Asset are non-disjoint sub classes of dcat:Resource, albeit that the latter is such via being a sub class of dcat:Dataset which subclasses dcat:Resource, means that resources could easily be dually typed as being of both prof:Profile and adms:Asset.

As prof:Profile is said not to be a subclass of dcat:Dataset (so I guess it is disjoint from it), whereas adms:Asset is a subclass of dcat:Dataset, I don't see how a profile can be also an adms:Asset (which I think it is).

Is there a strong motivation why prof:Profile shouldn't be made a subclass of dcat:Dataset?

**Comment by nicholascar** [comment]
@andrea-perego:

> As `prof:Profile` is said not to be a subclass of `dcat:Dataset` (so I guess it is disjoint from it), whereas `adms:Asset` is a subclass of `dcat:Dataset`, I don't see how a profile can be also an adms:Asset (which I think it is).

Since `prof:Profile` is not declared as disjoint with `dcat:Dataset`, you can't conclude (guess) that it is disjoint, only that it's not been declared a subclass/equivalent etc. So, the logic holds here that, as I originally wrote, "...resources could easily be dually typed as being of both `prof:Profile` and `adms:Asset`".

> Is there a strong motivation why `prof:Profile` shouldn't be made a subclass of `dcat:Dataset`?

Only the general sense that a Profile isn't necissarily a Dataset. Again, Profile it's not declared not a Dataset, just no strong commitment is made.

**Comment by andrea-perego** [comment]
@nicholascar said:

> Since prof:Profile is not declared as disjoint with dcat:Dataset, you can't conclude (guess) that it is disjoint, only that it's not been declared a subclass/equivalent etc. 

Probably not formally, but the note to the PROF - DCAT alignment says:

> prof:Profile is not a sub class of dcat:Dataset

which means that a profile is not a dataset.

So, I think the point needs to be clarified, or the statement above relaxed.

Said that, happy to approve this PR provided that this issue is addressed for the next release.

**Review by andrea-perego — APPROVED** [review]

**Review by rob-metalinkage — APPROVED** [review]
thanks.  note that the comments relating to DCAT alignment need to be picked up in issue #808. Note that DCAT alignment is non-normative - so its up to implementors to decide if they want a Profile to be equivalent to a Dataset.

**Pull request merged**
