### PR TITLE
DCAT remove at risk notes

### PR DESCRIPTION
**Pull request by davebrowning**
As title

### CODE REVIEW

**Comment by davebrowning** [comment]
Preview at http://raw.githack.com/w3c/dxwg/dcat-remove-at-risk-notes/dcat/index.html

**Comment by davebrowning** [comment]
And how it would look as a PR:

http://raw.githack.com/w3c/dxwg/dcat-remove-at-risk-notes/dcat/index.html?specStatus=PR;crEnd=2019-10-31;prEnd=2019-12-12;publishDate=2019-11-19

**Comment by davebrowning** [comment]
@agbeltran - this doesn't do your affiliation change.....

**Review by riccardoAlbertoni — APPROVED** [review]

**Comment by agbeltran** [comment]
@davebrowning  no problem, I have another branch for that, which I can update after this gets merged

**Review by agbeltran — APPROVED** [review]

**Pull request merged**
