### PR TITLE
Updated namespace file

### PR DESCRIPTION
**Pull request by davebrowning**
Updates namespace file for DCAT 2, supporting both the new rec and the older 2014 one, as per #377

### CODE REVIEW

**Comment by dr-shorthair** [comment]
There is a note at the beginning of the formal specification https://w3c.github.io/dxwg/dcat/#RDF-representation inserted early in our drafting which suggests that the RDF representation would be modularized. 
This was mostly in relation to a possible dcat-prov alignment axiomatization, also dcat-schema.org, but also potentially related to a DCAT-2014 profile. So we need to consider if these are good, and whether they are normative, and have a story about them to drop into this artefact?

**Comment by dr-shorthair** [comment]
Needs to also provide links to:
- https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat-prov.ttl 
- https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat-schema.ttl

We also need to decide if these are normative or non-normative

**Review by dr-shorthair — APPROVED** [review]

**Comment by davebrowning** [comment]
This comment summarises our intentions here.

The 2014 recommendation contains links to the namespace page at `https://www.w3.org/ns/dcat#`.  (For example, in the Class tables at https://www.w3.org/TR/2014/REC-vocab-dcat-20140116/#class-catalog.).  By default this returns a simple namespace page that provides links to the rdf definitions in either turtle or rdf/xml.  The namespace also supports these alternate forms directly via the `link` header.

DCAT2 uses the same name space (so we aren't introducting a new version in the URI) and we are providing replacement turtle and rdf/xml that are backward compatible, some other representations/encodings and a new namespace file.  Simply renaming the existing resources (by addtition of 2014 perhaps) and replacing them with new resources means that links from the 2014 spec will show the new resources.  Is this acceptable?   We can ensure that the turtle. etc  files and the namespace page include appropriate text to guide any human user, but we'd appreciate guidance on doing this for machine access.  Is something like ADMS (e.g. https://www.w3.org/TR/vocab-adms/#adms-last) appropriate and/or required ?  What would this mean for what we'd need to release?

**Comment by riccardoAlbertoni** [comment]
> Needs to also provide links to:
> 
> * https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat-prov.ttl
> * https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat-schema.ttl
> 

As discussed in #725, we should also add a reference to 
 * https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat-external.ttl

and as discussed in a teleconference ( I can't recall which one) we might want to refer to the former 
 version of dcat as well.
* https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat2014.ttl 

> We also need to decide if these are normative or non-normative

I think they are all non-normative.

**Comment by davebrowning** [comment]
And it should probably link to the json-ld examples from #1062 as well.

Actually - are we happy that those links are to the master branch in github....?  Might be easier to manage if the 'live' versions were served from the W3 system that holds the actual req.

**Comment by davebrowning** [comment]
I don't think this is yet complete, but wanted to open it to wider review.  It can be seen at
https://raw.githack.com/w3c/dxwg/dcat-namespace-page/dcat/rdf/dcat.html

At this stage, the idea is that the namespace file would replace the existing one at https://www.w3.org/ns/dcat.html.  In addition, we would release (also in  https://www.w3.org/ns)

1. A new version of the file dcat.ttl (containing the V2 ttl) overwriting the 2014 one
2. A new version of the file dcat.rdf (containing the V2 RDF/XML) overwriting the 2014 one
3. A copy of the 2014 turtle called dcat2014.ttl
4. A copy of the 2014 RDF/XML called dcat2014.rdf.
5. A copy of the documentation in dcat-external.ttl

If we add a json-ld version  (as suggested in #1062 [here](https://github.com/w3c/dxwg/pull/1062#issuecomment-532683222) then it would follow the same pattern.

We do need to decide whether the examples directory is published onto the webserver or whether we just link back to github.  If we do publish onto the server then we probably need to consider a sensible directory structure.  At the moment we are linking to github gh-pages branch.

Comments & improvements please...

**Comment by davebrowning** [comment]
Links for rdf/xml and jsonld versions of current RDF added (those files to be provided as part of #1062).

**Review by riccardoAlbertoni — APPROVED** [review]

**Comment by riccardoAlbertoni** [comment]
> We do need to decide whether the examples directory is published onto the webserver or whether we just link back to github.

I think linking to github might be enough, but I am open to other views.

**Comment by kcoyle** [comment]
I'll add the question of publishing examples (github or ??) to the list of questions that Peter and I are keeping. We'll need to get together with Philippe for these, so let us know if you have others.

**Comment by davebrowning** [comment]
> 
> I think linking to github might be enough, but I am open to other views.

I'm coming round to that view - originally I was concerned on how the 'evergreen' process might work in github if gh-pages (ie the master) is live.  There are ways to manage that but it kind of depends on how 'continuously integrated' the evergreen process intends to be.  [Jumping ahead, of course.....]

**Review by rob-metalinkage — APPROVED** [review]
I _think_ i approve - but this PR has some rather involved discussion and its not very easy to see a summary of what exactly is proposed beyond the sub-groups recommendation to update the content the namespace resolves to in a backwards compatible way. If there is more to it than that it probably needs to be made clearer.

**Comment by davebrowning** [comment]
@rob-metalinkage Thanks.  At the moment the primary aim is to make sure we don't break backward compatibility.  

If there is a need to provide support for people using these automatically, then I'd hope we can progress that since it wouldn't be part of the actual recommendation (so could be treated as a 'WG note' kind of activity).  Of course, we should probably get better guidance/feedback on that  as we go through the CR stage.  As it is this is (IMHO) providing equivalence to 2014, and is broadly in line with what I can see other WGs have published in the last 12/18 months

**Pull request merged**
