### PR TITLE
Refine the config.js

### PR DESCRIPTION
**Pull request by dr-shorthair**
Some tweaks in response to #184 
But not clear about the URIs for this version vs. the prior version. 
WIll need guidance from @draggett

### CODE REVIEW

**Comment by agbeltran** [comment]
When referring to the new DCAT version we might need to remove 1.1 and add 'DCAT revision' or similar. This should be modified after today's meeting.

**Comment by dr-shorthair** [comment]
@agbeltran I believe this PR removes all mention of DCAT 1.0 and DCAT 1.1 including in the title. 
It consistently replaces them with 'DCAT 2014' and 'revision of DCAT' instead.

**Comment by agbeltran** [comment]
Thanks, when referring to DCAT (the new version) should we say DCAT rev all along? I can merge and then we refine if needed.

**Review by agbeltran — APPROVED** [review]

**Comment by dr-shorthair** [comment]
rE #147

**Pull request merged**
