### PR TITLE
 Issue 1252 first solution- adding the dcterms:creator arrow from dcat:Catalog to foaf:Agent

### PR DESCRIPTION
**Pull request by riccardoAlbertoni**
To make figure 1 more consistent according to remarks made in #1252, I have added the dcterms:creator arrow from dcat:Catalog to foaf:Agent.
The UML diagram is not normative, and it tries to give an overview of the main properties/entities in DCAT.  
As far as I remember there is no specific reason why dcterms:publisher had an explicit arrow besides being listed in the properties and dcterms:creator has not. 

If the other contributors prefer an alternative to this solution could have been deleting the arrow for dcterms:publisher from dcat:Catalog to foaf:Agent.

Preview: https://raw.githack.com/w3c/dxwg/dcat-issue-1252/dcat/index.html#dcat-scope

### CODE REVIEW

**Review by davebrowning — APPROVED** [review]

**Comment by andrea-perego** [comment]
@riccardoAlbertoni said:

> To make figure 1 more consistent according to remarks made in #1252, I have added the dcterms:creator arrow from dcat:Catalog to foaf:Agent.
> The UML diagram is not normative, and it tries to give an overview of the main properties/entities in DCAT.
> As far as I remember there is no specific reason why dcterms:publisher had an explicit arrow besides being listed in the properties and dcterms:creator has not.
> 
> If the other contributors prefer an alternative to this solution could have been deleting the arrow for dcterms:publisher from dcat:Catalog to foaf:Agent.

Probably we should indeed remove `dcterms:publisher` from `dcat:Catalog`.

**Comment by riccardoAlbertoni** [comment]
> Probably we should indeed remove `dcterms:publisher` from `dcat:Catalog`.

I have just implemented this alternative with Pr #1400. I am fine with either way.

**Comment by davebrowning** [comment]
So this PR is superfluous now?

**Comment by riccardoAlbertoni** [comment]
> So this PR is superfluous now?

I think so.

**Pull request closed without merging**
