### PR TITLE
Revision to UC19

### PR DESCRIPTION
**Pull request by andrea-perego**
Following [ACTION-59](https://www.w3.org/2017/dxwg/track/actions/59) (still pending review).

This revision was proposed on 23 Jan 2018 - see [the relevant email](https://lists.w3.org/Archives/Public/public-dxwg-wg/2018Jan/0079.html).

No positive / negative feedback so far. Please consider merging.

### CODE REVIEW

**Review by dr-shorthair — APPROVED** [review]
OK

**Comment by andrea-perego** [comment]
@dr-shorthair , @jpullmann , do you think I can go ahead and merge it, or should I wait also for the approval of UCR editors?

**Comment by kcoyle** [comment]
I believe that use cases need to be agreed by the plenary, as part of the consensus process. I'll try to understand if we approved this use case in the past (our records are a bit unclear).

**Comment by agbeltran** [comment]
Apart from agreeing on use cases on the plenary, our [Github etiquette](https://www.w3.org/2017/dxwg/wiki/GitHub_etiquette) requires the editors of the UCR to merge the PR.

**Comment by rob-metalinkage** [comment]
Waiting to hear from check if agreed in plenary.

**Comment by andrea-perego** [comment]
@agbeltran , my request was actually because this PR was hanging on for more than 1 month with no feedback besides @dr-shorthair 's.

@kcoyle , just for clarity's sake, this is not a new UC, but one contributed during the very first phase of the UC collection. Based on my records, the UC was approved, modulo being revised as per [ACTION-59](https://www.w3.org/2017/dxwg/track/actions/59). ACTION-59 also list the relevant emails. As I said in [this email](https://lists.w3.org/Archives/Public/public-dxwg-wg/2017Nov/0115.html), 

> [...] this use case is a generalisation of other 4 more specific use cases I contributed, covering data lineage [[1](https://w3c.github.io/dxwg/ucr/#ID12)], agent roles [[2](https://w3c.github.io/dxwg/ucr/#ID13)], data quality [[3](https://w3c.github.io/dxwg/ucr/#ID14)], and conformity [[4](https://w3c.github.io/dxwg/ucr/#ID16)]. Moreover, UC5.32 [[5](https://w3c.github.io/dxwg/ucr/#ID32)], contributed by Alejandra, is also related. [...]

The UC has been revised as agreed, and the revision contributed on [23 Jan 2018](https://lists.w3.org/Archives/Public/public-dxwg-wg/2018Jan/0079.html). As I didn't receive any feedback, I decided to proceed with a PR to trigger comments (if any).

**Comment by dr-shorthair** [comment]
@kcoyle @pwin can this be merged?

**Comment by kcoyle** [comment]
@rob-metalinkage @jpullmann This is a UCR issue, which you should sign-off on (merge).

**Pull request merged**
