### PR TITLE
First take at conneg-by-http

### PR DESCRIPTION
**Pull request by larsgsvensson**
https://raw.githack.com/w3c/dxwg/larsgsvensson-patch-2/conneg-by-ap/index.html

### CODE REVIEW

**Comment by nicholascar** [comment]
For the Issue that you introduced, can you create an Issue in GitHub and then assign the number to the Issue in the doc and label it like the others with data-number so we it in the list of profile-negotiation taggged Issues?

**Comment by larsgsvensson** [comment]
Just created #500 and #501

**Comment by larsgsvensson** [comment]
Last commit was adding the privacy and security section

**Comment by larsgsvensson** [comment]
cf. https://github.com/w3c/dxwg/issues/364#issuecomment-433464596

**Pull request merged**
