### PR TITLE
PR Issue 1443 - renaming prev, next, last, first into previousInSeries..ect

### LINKED ISSUE #1443: Properties relating to series can be confused with those for versions
For a cataloged resource, previous and first and last properties can easily be confused with versions. Would it be more helpful to users if we called them previousInSeries, firstInSeries, lastInSeries?

### PR DESCRIPTION
**Pull request by riccardoAlbertoni**
closes #1443

### CODE REVIEW

**Comment by riccardoAlbertoni** [comment]
Still to decide whether or not  dropping the occurences of "ordered collections" in the definitions of  previousInSeries, firstInSeries, lastInSeries.

**Review by andrea-perego — COMMENTED** [review]
I suggest we keep this PR on hold until we discuss the overall issue in the subgroup meeting.

**Review by dr-shorthair — APPROVED** [review]

**Comment by riccardoAlbertoni** [comment]
> I suggest we keep this PR on hold until we discuss the overall issue in the subgroup meeting.

Yes, I agree we  need to discuss this PR in the DCAT call. I have just noticed some choices that we might need to doublecheck  before any merging.

**Comment by agreiner** [comment]
I'm having a hard time thinking of an example of an ordered collection that would not be a series.

**Comment by riccardoAlbertoni** [comment]
Do not merge!
According to resolution  https://www.w3.org/2022/02/22-dxwgdcat-minutes#r04
an alternative PR will be prepared adding to dcat:prev etc. properties an explanation of which is their scope and purpose, and why they are associated with dcat:Resource. [in short, they are  used in dataset series but they are not only for dataset series]

**Pull request closed without merging**
