### PR TITLE
Reflect resolution of #172 into ED.

### PR DESCRIPTION
**Pull request by dr-shorthair**
Some changes to notes and issues in the ED reflecting the resolutions in today's DCAT telecon. 
These resolutions were after the vote to move the ED to FPWD, so not sure if they should be accepted into the ED for snapshot as FPWD. In the meeting we agreed that the editors have some prerogative here, but I'll let the other editors make a call.

### CODE REVIEW

**Comment by andrea-perego** [comment]
I suggest we include them in the next WD iteration.

**Comment by agbeltran** [comment]
@andrea-perego why do you suggest to wait? If the changes were approved, it might be good to mention that these changes will occur (the changes have not been implemented, only the document has been modified to indicate that the changes will be implemented as far as I can tell). Thanks

**Comment by andrea-perego** [comment]
@agbeltran , I suggested we wait since how the relevant issues will be actually addressed is still under discussion, so I was thinking it would be a bit premature to include their description in the FPWD.

Said that, I wouldn't object if the Editors decide otherwise.

**Comment by dr-shorthair** [comment]
The changed document can be inspected here: 
https://rawgit.com/w3c/dxwg/dcat-catalog-scope-simon/dcat/index.html 

Changes are made here:
https://rawgit.com/w3c/dxwg/dcat-catalog-scope-simon/dcat/index.html#vocabulary-overview and 
https://rawgit.com/w3c/dxwg/dcat-catalog-scope-simon/dcat/index.html#class-catalog

**Comment by dr-shorthair** [comment]
AFAICT there were no objections to including this change in the version for FPWD. 
Perhaps one of the editors can merge?

**Review by davebrowning — APPROVED** [review]
Agreed - as discussed in  the first part of  today's plenary, this matches the agreed state before the resolution on short urls

**Comment by dr-shorthair** [comment]
Re #147

**Pull request merged**
