### PR TITLE
Dcat issue837 mentioning DCAT Future Priority

### PR DESCRIPTION
**Pull request by riccardoAlbertoni**
Addressing issue #837 , an attempt to  rephrase  the sentence, backlog is now DCAT Future Priority,  as it was decided in [the DCAT teleconference](https://www.w3.org/2019/03/27-dxwgdcat-minutes#x08).

### CODE REVIEW

**Comment by davebrowning** [comment]
Marked as non substantive for IPR from ash-nazg.

**Review by davebrowning — CHANGES_REQUESTED** [review]
Minor typo - "belive" - but otherwise fine

**Comment by riccardoAlbertoni** [comment]
> Minor typo - "belive" - but otherwise fine

thanks, @davebrowning,  Corrected!

**Review by davebrowning — APPROVED** [review]

**Review by dr-shorthair — APPROVED** [review]
I made some minor changes to smooth the language.

**Pull request merged**
