### PR TITLE
DCAT issue 751 - accessService is not sub-property of accessURL

### PR DESCRIPTION
**Pull request by dr-shorthair**
Addressing #751

### CODE REVIEW

**Review by agbeltran — CHANGES_REQUESTED** [review]
I suggest we change

"dcat:accessURL generally matches the property-chain dcat:accessService/dcat:endpointURL. In the RDF representation of DCAT this is axiomatized as an OWL property-chain axiom."

for 

"dcat:accessURL matches the property-chain dcat:accessService/dcat:endpointURL. In the RDF representation of DCAT this is axiomatized as an OWL property-chain axiom."

as the axiom is included, we can safely remove 'generally'?

I'd also use the Manchester OWL Syntax for the property chain 'dcat:accessService o dcat:endpointURL'

This property chain implies some domains/ranges that are not explicitly stated - do we want to do include them?

**Comment by agbeltran** [comment]
@dr-shorthair let me know what you think about the suggestions in the review - I could implement the changes

**Comment by dr-shorthair** [comment]
Thanks @agbeltran. Yes I agree with your suggestions. Should indicate what the notation used is. 

(Would be nice to have all the example available in alternative syntaxes. We all like Turtle, but the market is looking for JSON. Like here: https://www.w3.org/TR/owl2-primer/#OWL_Syntaxes )

**Review by agbeltran — APPROVED** [review]

**Comment by agbeltran** [comment]
Addressed the very minor text change - we can address the different syntaxes in a separate issue.

**Pull request merged**
