### PR TITLE
DCAT: Editorial fixes

### PR DESCRIPTION
**Pull request by andrea-perego**
Preview: https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html

HTML diff:

https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fdxwg%2Fdcat%2Findex.html&doc2=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fdxwg%2Fandrea-perego-dcat-ed-rev%2Fdcat%2Findex.html

Summary of changes:

- https://github.com/w3c/dxwg/pull/919/commits/973de8c76575d47303dafab98f9c460a30c0f476 :
  - Removed usage note from `dcat:startDate` / `dcat:endDate`, and updated their range, consistently with other properties using a datetime format
  - Minor editorial fixes
- https://github.com/w3c/dxwg/pull/919/commits/ed7862da4ebb2c1fa3c8ddee735840c358ed2143 :
  - Moved section and references to `dcat:bbox` just after `locn:geometry`
  - Extended note in [Section 11.2](https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html#spatial-properties) with additional pointers to SDWBP
- https://github.com/w3c/dxwg/pull/919/commits/9510be815be30f173f56019be7ff4c358f08abc1 : Added `class="nohighlight turtle"` to all PRE elements
- https://github.com/w3c/dxwg/pull/919/commits/ff50631e9b2579d0de2c1a2f298096f73635b58e : Fixed typo reported in https://github.com/w3c/dxwg/issues/922 :
  > Minor type in the usage note for spatial resolution: "For other kinds of spatial dataset," should probably be "For other kinds of spatial datasets,"
- https://github.com/w3c/dxwg/pull/919/commits/7a7239cfdd6fe6df63cde9728b1768f100c8531e : Addressed issue reported in https://github.com/w3c/dxwg/issues/922 :
  > dcat:compressFormat and dcat:packageFormat: There is no note that those were added during the revision.
- https://github.com/w3c/dxwg/pull/919/commits/ee27db4f68dc8fc94a36a7536d36cba442fec87c : Fixed typo Reported in #922:
  > dcat:Role: The note says that the property was newly added, but dcat:Role is a class...
- https://github.com/w3c/dxwg/pull/919/commits/beaa0b34d5b5631f897ed75152ad2acd15c7b09d : Added link to DCAT Turtle file in `config.js` as an attempt to address the comment reported in https://github.com/w3c/dxwg/issues/922:
  > In the last part of the abstract it says "The (revised) DCAT vocabulary is available here." IIRC hyperlinks with the text "here" are considered a Bad Practice (TM). Suggestion "There is a Turtle version of the (revised) DCAT vocabulary available".
- https://github.com/w3c/dxwg/pull/919/commits/8abf869af3e745340b78b840a74abf034aa4d5cc : Removed duplicate DATS entry and updated URL, as per https://github.com/w3c/dxwg/issues/895
- https://github.com/w3c/dxwg/pull/919/commits/62f3438ed4fc9fdf95460d1e68e63f0173a64412 :
  - Reorganised sections to address #918
  - Made sections 7-14, B, C "informative" to address the issue reported in #922:
    > Are the sections on Qualified Relations, License and rights statements, Versioning and DCAT Profiles really all normative? They do not say non-normative so by reverse conclusion they are...
- https://github.com/w3c/dxwg/pull/919/commits/f402b2e543afa44471845e6febcfef61677ce099 : Harmonised NOTEs marking new property and classes, to address #923
- https://github.com/w3c/dxwg/pull/919/commits/65b47d9e9020bd68ca7360821efadf1ffc05b49b : 
  - s/catalogued/cataloged/
  - s/cataloguing/cataloging/
- https://github.com/w3c/dxwg/pull/919/commits/39db902412b004e79a6bb527b3c7b5496d2228d4 : Editorial changes to change history and section about property `dct:isReferencedBy`
- https://github.com/w3c/dxwg/pull/919/commits/b194250e088c02d822ce4d7da18adb47955e5d83 : Removed NOTE in Conformance section, as per https://github.com/w3c/dxwg/issues/918#issuecomment-491585729
- https://github.com/w3c/dxwg/pull/919/commits/4074c9444dd6bd9c6656f4e21a1234e18a6949d0 : Updated NOTE for class Catalog, and added related entry in change history, as per https://github.com/w3c/dxwg/issues/918#issuecomment-491542091
- https://github.com/w3c/dxwg/pull/919/commits/a84b690c4d8fd730f832c905f52876e64031db11 : Editorial fix to address https://github.com/w3c/dxwg/issues/923#issuecomment-491611452
- https://github.com/w3c/dxwg/pull/919/commits/39230b04871a57d715cd27f1c1f7736bc0a48d6d : Added `dc` to namespace table, as suggested by @davebrowning 
- https://github.com/w3c/dxwg/pull/919/commits/b3158d6c80febbba2ef5c76d7763ac4951f67464 : Added `geosparql` in namespace table
- https://github.com/w3c/dxwg/pull/919/commits/d744c8be8935172c47bb5c762df0b3f85fb74e15 : Removed NOTE in Versioning section, as per https://github.com/w3c/dxwg/issues/918#issuecomment-491507848
- https://github.com/w3c/dxwg/pull/919/commits/fc8e3a156d8b0f44a9a1d9d336abd83475fe43a3 : Removed last sentence in abstract pointing to `dcat.ttl` file, as proposed in https://github.com/w3c/dxwg/issues/922#issuecomment-491758757
- https://github.com/w3c/dxwg/pull/919/commits/ac198c647b649a7828840e3e6864dd61f7ec901f : Fixed bib refs making DQV a normative ref
- https://github.com/w3c/dxwg/pull/919/commits/2f79ace948358ad7d394099b5ae8fdb1a19d09a4 : Fixed typo reported in #922:
  > Just above Example 4 the text says "a 5Kb CSV file". Should that be "a 5 kB CSV file"? (minor k for prefix kilo)
- https://github.com/w3c/dxwg/pull/919/commits/67b85709f703ec38677f7c089e88394efd59762b : Harmonised fragment identifier patterns for sections about classes and properties
- https://github.com/w3c/dxwg/pull/919/commits/2748ad8cb4ea94601222e4d06e9afe8d99b2da84 : Made informative SPARQL11-QUERY and VOCAB-ORG bib refs
- https://github.com/w3c/dxwg/pull/919/commits/132f35597c41d03605685e316cd617dafeb97c66 : Added link to issue in changelog entry about class Catalog
- https://github.com/w3c/dxwg/pull/919/commits/47b312d6012ab346bfdbb0cb83b0f1069ef4e91b : Added `w3cid` field for editors in `config.js`, and field `formerEditors` (replacing the relevant entries in `otherLinks`)

### CODE REVIEW

**Comment by dr-shorthair** [comment]
Also should update scopeNote in dcat.ttl to match.

**Comment by davebrowning** [comment]
@dr-shorthair 

> Also should update scopeNote in dcat.ttl to match.

Which reminds me that the editorialNotes in dcat.ttl need reviewing/revising (as does the `owl:versionInfo`) to reflect the current status/where we've got agreement.  More I look more I see so I've opened #920 to track - probably not a good idea to include it in this PR.

**Comment by andrea-perego** [comment]
I wonder whether we should wait to update dcat.ttl until we have the final version of the spec.

After all, the HTML is the normative version, so maybe we can complete the alignment of dcat.ttl also after releasing the CR.

**Comment by davebrowning** [comment]
@andrea-perego 

> I wonder whether we should wait to update dcat.ttl until we have the final version of the spec.
> 
> After all, the HTML is the normative version, so maybe we can complete the alignment of dcat.ttl also after releasing the CR.

True, but we have to do it sometime.  (Also, I've started :smiley:).  There are two immediate things - some of the editorialNotes are now outdated (I think - if they aren't then I'm confused), and some changeNotes are missing on some new properties. Was hoping we could fix those (we won't need to revisit).

Translations can wait I think.

**Review by davebrowning — APPROVED** [review]
One minor point - I think we should add `dc: <http://purl.org/dc/elements/1.1/>` to the namespace list since its used in examples directly (as per discussion [here](https://github.com/w3c/dxwg/issues/922#issuecomment-490630182).  It's already present in dcat.ttl - I guess that's where Lars saw it.

**Comment by andrea-perego** [comment]
@davebrowning said:

> One minor point - I think we should add `dc: <http://purl.org/dc/elements/1.1/>` to the namespace list since its used in examples directly (as per discussion [here](https://github.com/w3c/dxwg/issues/922#issuecomment-490630182). It's already present in dcat.ttl - I guess that's where Lars saw it.

Done via https://github.com/w3c/dxwg/pull/919/commits/39230b04871a57d715cd27f1c1f7736bc0a48d6d

On a related note: I wonder whether, after all, we should make the Namespaces section "informative" - as it does not include only namespaces used in DCAT (or used to define terms in the DCAT namespace).

**Comment by dr-shorthair** [comment]
Maybe the table should be split in two and put in two subsections : the namespaces that are used in chapter 6 (normative) and the ones occurring in the examples (informative)

**Comment by davebrowning** [comment]
> Maybe the table should be split in two and put in two subsections : the namespaces that are used in chapter 6 (normative) and the ones occurring in the examples (informative)

:+1: I think that's worth it - it would make it clearer to my reading.

So I think that means that `adms:`, `dc:`, `dqv:`, `earl:`, `oa:`, `sdmx-attribute:`, and `sdo:`  turn up as non-normative.  [And I should remove `dc:` from the ttl in #926 - it was used in DCAT 2014 but its no longer used directly, even in string text]

**Comment by andrea-perego** [comment]
I am concerned this will make the consultation less easy - I may need to check in two different tables to find what I'm looking for.

**Comment by davebrowning** [comment]
> I am concerned this will make the consultation less easy - I may need to check in two different tables to find what I'm looking for.

Good point

**Review by riccardoAlbertoni — APPROVED** [review]

**Comment by andrea-perego** [comment]
I've just realised we lost `geosparql` from the namespace table. 

Added via https://github.com/w3c/dxwg/pull/919/commits/b3158d6c80febbba2ef5c76d7763ac4951f67464

**Comment by dr-shorthair** [comment]
> I may need to check in two different tables to find what I'm looking for. 

Yeah - but they would be right next to each other. The suggestion is only that chapter 3 has two subsections, one normative, the other informative. The table has become very long now, and a lot of the entries are only to support one or two mentions in examples. These are not as interesting as the table that lists the namespaces that are involved in normative content in DCAT. People reading this document are already going to be jumping around (that's the nature of technical specifications, in contrast to a primer that should be consumable sequentially). Accuracy is paramount in a tech spec.

**Comment by andrea-perego** [comment]
Checking [the list of normative references](https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html#normative-references), there are some I'm not sure should be in - namely:
- [SPARQL11-QUERY]
- [VOCAB-ORG]

As far as I can see, they are not used in the definition of DCAT terms (also in terms of domain / range).

Should we make them "informative"?

**Comment by andrea-perego** [comment]
I think there's an issue it may be worth addressing before merging this PR, namely, the one in https://github.com/w3c/dxwg/issues/918#issuecomment-491609377

Basically:
- Are you happy with the revisions done in commit https://github.com/w3c/dxwg/commit/4074c9444dd6bd9c6656f4e21a1234e18a6949d0 ?
- Do you have any suggestions about the relevant issues we should point to for the following changes?
  - `dcat:Catalog` made a subclass of `dcat:Dataset`
  - addition of property `dct:hasPart`
  - addition of property `dcat:service` 
  - addition of property `dcat:catalog`

**Review by dr-shorthair — APPROVED** [review]

**Comment by andrea-perego** [comment]
> Checking [the list of normative references](https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html#normative-references), there are some I'm not sure should be in - namely:
> 
> * [SPARQL11-QUERY]
> * [VOCAB-ORG]
> 
> As far as I can see, they are not used in the definition of DCAT terms (also in terms of domain / range).
> 
> Should we make them "informative"?

Done via https://github.com/w3c/dxwg/commit/2748ad8cb4ea94601222e4d06e9afe8d99b2da84 , following the decision during the 15 May [DCAT subgroup call](https://www.w3.org/2019/05/15-dxwgdcat-minutes).

**Comment by andrea-perego** [comment]
I suggest we merge this PR now as is. I will address the revision of the Namespaces section in a separate one.

**Comment by andrea-perego** [comment]
> I think there's an issue it may be worth addressing before merging this PR, namely, the one in [#918 (comment)](https://github.com/w3c/dxwg/issues/918#issuecomment-491609377)
> 
> Basically:
> 
> * Are you happy with the revisions done in commit [4074c94](https://github.com/w3c/dxwg/commit/4074c9444dd6bd9c6656f4e21a1234e18a6949d0) ?

Approved during the 15 May [DCAT subgroup call](https://www.w3.org/2019/05/15-dxwgdcat-minutes).

> * Do you have any suggestions about the relevant issues we should point to for the following changes?
>   
>   * `dcat:Catalog` made a subclass of `dcat:Dataset`
>   * addition of property `dct:hasPart`
>   * addition of property `dcat:service`
>   * addition of property `dcat:catalog`

After further checking the issue base, I think we can point to the following issue: #172 (which also points to the relevant discussion in PR #241).

**Comment by andrea-perego** [comment]
> > * Do you have any suggestions about the relevant issues we should point to for the following changes?
> >   
> >   * `dcat:Catalog` made a subclass of `dcat:Dataset`
> >   * addition of property `dct:hasPart`
> >   * addition of property `dcat:service`
> >   * addition of property `dcat:catalog`
> 
> After further checking the issue base, I think we can point to the following issue: #172 (which also points to the relevant discussion in PR #241).

Done in https://github.com/w3c/dxwg/pull/919/commits/132f35597c41d03605685e316cd617dafeb97c66

**Comment by andrea-perego** [comment]
@riccardoAlbertoni , @davebrowning , @agbeltran , @dr-shorthair , @pwin ,

I added your w3cid in `config.js` via https://github.com/w3c/dxwg/pull/919/commits/47b312d6012ab346bfdbb0cb83b0f1069ef4e91b

Please check they are the correct ones.

**Review by dr-shorthair — APPROVED** [review]

**Pull request merged**
