### PR TITLE
Dcat issue53 riccardo

### PR DESCRIPTION
**Pull request by riccardoAlbertoni**
Dear all, 
I have prepared a new  branch adding a section for DCAT identifiers,  which is related to issues #53 #68 #67.

Please don't merge until the group has revised it.

The proposed new section distils [proposal 2 in the wiki](https://github.com/w3c/dxwg/wiki/DCAT-Identifiers#proposal-2-it-revises-and-reassembles-proposal-1) and considers some of the input received during the last dcat call ( [28-11-2018 meeting minutes ](https://www.w3.org/2018/11/28-dxwgdcat-minutes)).  In particular, 

- It does not explicitly mention primary and secondary IDs,
- it deals with IDs in general not only for datasets, 
- it only refers the dcat-ap guidelines about dataset duplications.

I suggest to accept this section as a first attempt to solve the aforementioned issues, and then change/ drop any part the group might want. 

 I'd invite @agbeltran and @makxdekkers, who have made suggestions during the last call, to chime in and change the pull if I have not satisfactorily  embodied their suggestions.

Cheers, 
Riccardo

### CODE REVIEW

**Comment by agbeltran** [comment]
This is great @riccardoAlbertoni, thanks. 

Dropping here the link to visualise the new section:

https://rawgit.com/w3c/dxwg/dcat-issue53-riccardo/dcat/index.html#Dereferenceable-identifiers

and the differences with the Editor Draft:

https://services.w3.org/htmldiff?doc1=http%3A%2F%2Fw3c.github.io%2Fdxwg%2Fdcat%2F&doc2=https%3A%2F%2Frawgit.com%2Fw3c%2Fdxwg%2Fdcat-issue53-riccardo%2Fdcat%2Findex.html

**Comment by smrgeoinfo** [comment]
thanks @riccardoAlbertoni, looks good to me.

**Comment by makxdekkers** [comment]
The new text states: "_The need to clearly distinguish between primary and legacy identifiers for a dataset has been identified as a requirement to be satisfied in the revision of DCAT_". 
I am not entirely in agreement with that.
I would say that, yes, there is a need for such a distinction in particular cases, i.e. in harvesting environments where descriptions are copied among catalogues. This case is mentioned in the last sentence of the section: "_Depending on the application context, specific guidelines such as "DCAT-AP: How to manage duplicates?" can be adopted for distinguishing authoritative datasets from dataset harvested by third parties catalogs_".
In my mind, the notion of primary and secondary (not **_legacy_**, I think) identifiers depends very much on the application environment. This requirement could be satisfied in a profile (as it is done on the EU DCAT-AP) and not in the base standard.

**Comment by agbeltran** [comment]
@makxdekkers we do have the requirement for primary and alternative identifier (see https://github.com/w3c/dxwg/issues/67) - if we delegate the solution to a profile, it is something we should clarify in the document as a way of addressing that requirement

**Review by agbeltran — CHANGES_REQUESTED** [review]
A comment on the DOI example. Instead of using a DOI that corresponds to a publication, can we use a DOI for a dataset? If the recommendation is to use owl:sameAs for the URI corresponding to the textual DOI, I suggest removing the part of the example that uses skos:notation

**Comment by agbeltran** [comment]
A comment on the DOI example. Instead of using a DOI that corresponds to a publication, can we use a DOI for a dataset? If the recommendation is to use owl:sameAs for the URI corresponding to the textual DOI, I suggest removing the part of the example that uses skos:notation

e.g. we could use https://doi.org/10.5281/zenodo.1486279

we could consider the schema.org version that they expose as a starting point:

```curl -LH "Accept: application/vnd.schemaorg.ld+json" https://doi.org/10.5281/zenodo.1486279```

**Comment by riccardoAlbertoni** [comment]
@agbeltran  I have just changed the example including the zenodo doi instead of ieee doi.

@ agbeltran wrote
> If the recommendation is to use owl:sameAs for the URI corresponding to the textual DOI, I suggest removing the part of the example that uses skos:notation

I suspect that some redudancy might help here.  In my view the owl:sameAs is an additional thing to say, which helps in retrieving more info about IDs.

**Comment by davebrowning** [comment]
Can I nudge this a little - I'd hoped we could discuss last night but we ran out of time.

@agbeltran : looks like @riccardoAlbertoni has addressed your review?

Looking at the thread in #67, it seems to have reached consensus that this contribution addresses the requirement (albeit by pointing out its actually context specific).  The one remaining thing would be to  use the phrase `alternative (legacy) identifiers` to bring it into line with the text in the [requirement](https://github.com/w3c/dxwg/issues/67)

**Comment by riccardoAlbertoni** [comment]
I have added the "use the phrase alternative (legacy) identifiers",  I suggest marking the issues #67 as due-for-closing ( as done by nick for issues in other documents) or if you prefer, closing the issue straight away.
If you are going to close, let me know that I will get rid of issue box in the document, copying its description in the text. 

 In both cases, please mention in the issue thread  the agreed conclusion, for example saying, "the group has agreed that  distinguishing between primary, secondary (alternative) identifiers it is very much application-specific and should be better addressed in application profiles rather than being mandate a general approach."

**Comment by davebrowning** [comment]
Thanks @riccardoAlbertoni, that's very helpful.  I'll ask the question about WG membership as a pre-req for being mentioned.  [Though in my quick survey I did see some examples where the contributors were not on the membership list..... but best to be sure.]

**Comment by davebrowning** [comment]
Thanks @riccardoAlbertoni - I have marked #67 as due for closing with the appropriate (provisional) conclusion.  Suggest we wait for a day or two to give people a chance to respond (ie disagree).

**Review by agbeltran — APPROVED** [review]

**Pull request merged**
