### PR TITLE
Remove superfluous note and stray figure

### PR DESCRIPTION
**Pull request by davebrowning**
Actions item 3 in PR #357 - needless note in vocal overview

### CODE REVIEW

**Comment by agbeltran** [comment]
@davebrowning are you saying that it is superflous because is the same as the one appearing in the dcat:Dataset section?

https://rawgit.com/w3c/dxwg/dcat-glitch-fix-daveb/dcat/index.html#Class:Dataset

isn't this the note added as per issue https://github.com/w3c/dxwg/issues/350 and PR https://github.com/w3c/dxwg/pull/351

?

**Comment by dr-shorthair** [comment]
I suggest either removing the first occurrence (in section 5) or cutting it down substantially.

**Comment by dr-shorthair** [comment]
ALso, need to remove Figure 2. 
I moved Figure 1 up to the top of the section, so it looks like the merge got confused.

**Comment by davebrowning** [comment]
I was suggesting that we drop the one in section 5. I think the subclass removal is adequately explained (and indeed more fully explained) in in the vocabulary definition itself (and noted in the change log at the back, which links to the original issue #98).  #350 and PR #351 added the extra detail to the vocab def NOTE.

More generally, I think the vocab overview (section 5) shouldn't go overboard in discussing changes cf 2014, but rather explains what the revised spec aims to achieve.  If that gets broken out into a separate doc/primer then that's fine by me, but we haven't discussed/agreed that approach.  For now, this is the only such NOTE in the vocab overview...

(Let me add the fix to the figures to this, too)

**Comment by dr-shorthair** [comment]
+1

**Comment by agbeltran** [comment]
+1

**Review by dr-shorthair — APPROVED** [review]

**Review by agbeltran — APPROVED** [review]

**Pull request merged**
