### PR TITLE
Add ref to #505 - order or precedence and remove MUST

### PR DESCRIPTION
**Pull request by rob-metalinkage**
no mechanism is available - tweaked #505 to make question clearer. 
Removed overspecification using MAY and MUST as per discussions in issue
Hopefully this also clarifies and addresses @agreiner concerns here.

### CODE REVIEW

**Review by agreiner — COMMENTED** [review]
If we go with the developer-must-also-create-standard approach, I would suggest saying "If other potentially conflicting functional profiles of the abstract model are defined, then order of precedence will need to be established." There's no need to make someone figure out all the possible combinations of ways others may have tried to code their APIs. In fact, without a mechanism for registering these, it would be impossible.

**Review by nicholascar — APPROVED** [review]

**Comment by nicholascar** [comment]
I've adopted @agreiner's suggested wording.

**Review by agreiner — CHANGES_REQUESTED** [review]
I don't see my suggested text in there.

**Comment by nicholascar** [comment]
We accepted both your suggestions and see https://github.com/w3c/dxwg/pull/1163/files#diff-530b9656f9dfedce3c4078b99c85686eR759, the sentence "If other potentially conflicting functional profiles of the abstract model are defined, then order of precedence will need to be established."  is now at line 759.

**Review by larsgsvensson — APPROVED** [review]
I approve the changes, although I'm always a bit hesitant to use passive constructs ("order of precedence will need to be established") since that does not make clear **who** is responsible for establishing this order.
I won't merge the commits, since I think we should wait for @agreiner's review before doing that.

**Review by agreiner — APPROVED** [review]
Interesting, that didn't show up in the changes shown when clicking "View Changes" until after my comment. Looks okay now.

**Pull request merged**
