### PR TITLE
This PR is to review and accept the Danish translation of DCAT

### PR DESCRIPTION
**Pull request by aidig**
Added Danish translation.

### CODE REVIEW

**Comment by riccardoAlbertoni** [comment]
Thank @aidig  for the translation.

For the other editors (@andrea-perego, @pwin, @agbeltran, @andrea-perego, @dr-shorthair)
The pull request simply translates every literal in Danish.  Considered that translations AFAIK are not normative, I think we can mark the pull request as "Mark as non-substantive" in terms of IPR and merge it.

**Review by riccardoAlbertoni — APPROVED** [review]

**Comment by andrea-perego** [comment]
> Thank @aidig for the translation.
> 
> For the other editors (@andrea-perego, @pwin, @agbeltran, @andrea-perego, @dr-shorthair)
> The pull request simply translates every literal in Danish. Considered that translations AFAIK are not normative, I think we can mark the pull request as "Mark as non-substantive" in terms of IPR and merge it.

+1 from me.

**Review by andrea-perego — APPROVED** [review]

**Comment by riccardoAlbertoni** [comment]
related to #174

**Comment by agbeltran** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by agbeltran** [comment]
thanks @aidig !

**Pull request merged**
