### PR TITLE
Additional scope note for hasPart, …

### PR DESCRIPTION
**Pull request by dr-shorthair**
drawing attention to the specific sub-properties

### CODE REVIEW

**Review by davebrowning — COMMENTED** [review]
Slightly confused on this, but perhaps that's because I'm ignorant on DC.  For example, in index.html, the URL http://purl.org/dc/terms/dataset gives me a file that doesn't mention dataset.  What am I missing?

**Comment by dr-shorthair** [comment]
Right. That's because the names and links are wrong 😕 should be dcat:dataset etc, not dct:dataset. Sorry. 

This is why we have a review phase... Easy enough to fix.

**Comment by dr-shorthair** [comment]
... Though not on a tablet. TTL also needs fixing

**Comment by dr-shorthair** [comment]
Fixed - see https://rawgit.com/w3c/dxwg/dcat-issue81-simon/dcat/index.html#Property:catalog_hasPart

**Review by davebrowning — APPROVED** [review]
Excellent

**Pull request merged**
