### PR TITLE
Text for Security and Privacy Section

### PR DESCRIPTION
**Pull request by davebrowning**
Aim to address #691.  

Draft questionnaire responses at https://www.w3.org/2017/dxwg/wiki/DCAT_Privacy_And_Security_Questionnaire

### CODE REVIEW

**Comment by davebrowning** [comment]
Changes all in section here: https://rawgit.com/w3c/dxwg/dcat-issue691-secpriv-daveb/dcat/index.html#security_and_privacy

Usuful to have review for accuracy - have I missed anything - before approach external group for specific expertise.

**Comment by agbeltran** [comment]
For the section to be ready, I think we should remove the reference to the issue in this PR.

**Comment by davebrowning** [comment]
> For the section to be ready, I think we should remove the reference to the issue in this PR.

I'd taken the view that leaving the issue link - with slight modified text - might make it easier for plenary to dig back into any discussion.  Once the merge was done, and the issue closed (spearate steps) we could do an editorial PR that removed all the closed issue notes still in the document.

But don't feel strongly either way.

**Comment by agbeltran** [comment]
I think that removing the issue from the spec will accelerate the process and avoid having to wait another week for editorial PR approvals in the next plenary meeting. 

The issue is linked in the PR (as you linked it above) and to see all the details, one needs to visit the issue anyway (as they are not in the spec anyway). So, I think it would be ok to remove the reference in the spec now.

**Comment by riccardoAlbertoni** [comment]
@agbeltran you are reading my mind, I am taking care of the issues ... see issues #838

**Comment by riccardoAlbertoni** [comment]
Though in my branches I have not considered instances of mention for issues that were not yet merged in the gh-pages as the one discussed here.

**Review by dr-shorthair — APPROVED** [review]

**Comment by davebrowning** [comment]
Issue reference removed as per above discussion

**Review by riccardoAlbertoni — APPROVED** [review]
I am not very familiar with the issues related to Security and Privacy, but the proposed text seems a fair attempt to address these issues. So it is ok for me, I think we can accept this and see if further suggestions arise from the enlarged group of members.

**Pull request merged**
